### ISSUE TITLE
Error while show content of vue file with Pug templater

### ISSUE THREAD

**Issue by Metotron** [sharkdp/bat#1614] opened 2021-04-20 10:35 UTC
Gen an error while open *.vue file with <template lang="pug"> in it:

thread 'main' panicked at 'Can only call resolve on linked references: ByScope { scope: <text.pug>, sub_context: None }', /home/abuild/rpmbuild/BUILD/bat-0.18.0/vendor/syntect/src/parsing/syntax_definition.rs:191:18
stack backtrace:
  0:     0x556532c47bc0 - < unknown >
  1:     0x556532b9b66c - < unknown >
  2:     0x556532c474a1 - < unknown >
  3:     0x556532c46ac1 - < unknown >
  4:     0x556532c64418 - < unknown >
  5:     0x556532c6438c - < unknown >
  6:     0x556532c6433d - < unknown >
  7:     0x556532c64300 - < unknown >
  8:     0x556532c7e0b1 - < unknown >
  9:     0x556532c7996f - < unknown >
10:     0x556532b3e4d9 - < unknown >
11:     0x556532b3300d - < unknown >
12:     0x556532acc9e0 - < unknown >
13:     0x556532ad4911 - < unknown >
14:     0x556532ad5da2 - < unknown >
15:     0x556532a98523 - < unknown >
16:     0x556532ad6409 - < unknown >
17:     0x7f06cf121b25 - __libc_start_main
18:     0x556532a9777e - < unknown >
19:                0x0 - < unknown >
bat 0.18.0 from OpenSUSE OSS-repo

**Comment by Enselic** [comment] 2021-04-20 18:56
Duplicate of #915

**Closed** 2021-04-21 13:29 UTC
Labels: bug
