### ISSUE TITLE
No output after resizing terminal window

### ISSUE THREAD

**Issue by tom-henderson** [sharkdp/bat#1128] opened 2020-08-04 20:59 UTC
**What version of `bat` are you using?**
bat 0.15.4

**Describe the bug you encountered:**
For some files, bat produces no output if the terminal window has been resized. For example `bat README.md` on this file https://github.com/tom-henderson/bookmarks/blob/master/README.md produces no output if the terminal has been resized. I assume this is related to the pager since ` bat --paging=never README.md` still works.

**Describe what you expected to happen?**
Bat would always produce output.

**How did you install `bat`?**
homebrew

---

system
------

**$ uname -srm**
Darwin 19.4.0 x86_64

**$ sw_vers**
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287

bat
---

**$ bat --version**
bat 0.15.4

**$ env**
BAT_THEME=Tomorrow-Night-Bright
BAT_PAGER=less -RF

**$ bat --list-languages**
Found custom syntax set.

**$ bat --list-themes**
Found custom theme set.

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 487 (POSIX regular expressions)

**Comment by sharkdp** [comment] 2020-08-15 13:13
Please see https://github.com/sharkdp/bat/issues/1053 and the issues linked under "Handling of terminal resize events". I am assuming this is a duplicate of those?

**Comment by tom-henderson** [comment] 2020-08-17 02:34
@sharkdp This might not be the same issue. I'm not resizing a window while bat is displaying a file. If I open a new window, resize it, and then use bat, some files will show no output.

**Comment by sharkdp** [comment] 2020-08-17 19:23
> This might not be the same issue. I'm not resizing a window while bat is displaying a file.

Oh, you are right. Sorry for closing this too quickly.

Could you please try to unset `BAT_PAGER`? `bat` should select `less` automatically. Your `less` version is quite old. If you unset `BAT_PAGER`, `bat` will provide all necessary command-line options for your version of less.

Even better would be to upgrade to a recent version of `less`.

I'm not sure if that would fix your problem, but it's worth a try. You could also try to display the file with `less -RF` after resizing the terminal.

**Comment by tigger04** [comment] 2020-08-17 21:25
I have exactly the same issue. Curiously less -RF appears to have the same issue, so I guess it's not exactly a bat defect

<img width="862" alt="image" src="https://user-images.githubusercontent.com/43514058/90445806-2fef6f80-e0d8-11ea-8128-64ddad539e3d.png">
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/43514058/90446009-85c41780-e0d8-11ea-9ca8-fcc1502cc255.png">

**Comment by tigger04** [comment] 2020-08-17 21:27
unsetting BAT_PAGER does seem to resolve it

<img width="730" alt="image" src="https://user-images.githubusercontent.com/43514058/90446177-d89dcf00-e0d8-11ea-9b5a-a4c7b3551646.png">

**Comment by tom-henderson** [comment] 2020-08-17 21:52
Ah yes so it looks like this issue is probably with `less -RF` and not with bat. Unsetting `BAT_PAGER` fixes this issue for me. 

I think I had originally set `BAT_PAGER` in order to get the scroll wheel working in iTerm2.

**Comment by sharkdp** [comment] 2020-08-18 05:31
Glad this could be resolved - thank you for the feedback!

The problem is that you have to pass `-X` for older versions of `less`, if you are also passing `-F`. If `BAT_PAGER` it not set, `bat` does this automatically. If `BAT_PAGER` is set, `bat` assumes that the user knows better and simply executes whatever has been set.

**Closed** 2020-09-20 18:44 UTC
Labels: question
