### ISSUE TITLE
Using Manpage language has errors in it

### ISSUE THREAD

**Issue by quintrino** [sharkdp/bat#1610] opened 2021-04-13 07:01 UTC
**Describe the bug you encountered:**
^H in Manpage formatting. 
...

**What did you expect to happen instead?**
It shouldn't show the ^H in the output. 
...

**How did you install `bat`?**
installed via brew
---

**bat version and environment**
bat 0.18.0

### Software version

bat 0.18.0

#### Operating system

Darwin 20.3.0

#### Command-line

```bash
bat --language manpage --diagnostic
```

#### Environment variables

```bash
SHELL=/usr/local/bin/zsh
PAGER=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=/Users/nick.wolf/.config
XDG_CACHE_HOME=/Users/nick.wolf/.cache
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='bat --language manpage --diagnostic'
```

#### Config file

Could not read contents of '/Users/nick.wolf/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Less version

```
> less --version
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```
<img width="564" alt="image" src="https://user-images.githubusercontent.com/7043587/114502718-916bdc00-9c6f-11eb-9a5c-68862603b108.png">

**Comment by keith-hall** [comment] 2021-04-13 19:43
Thanks for reporting. This looks like it could be a duplicate of https://github.com/sharkdp/bat/issues/652.

**Closed** 2021-05-12 10:02 UTC
Labels: bug, duplicate
