### ISSUE TITLE
Add Nim lang in default syntax 

### ISSUE THREAD

**Issue by raivivek** [sharkdp/bat#542] opened 2019-04-10 16:46 UTC
Hi, I think adding [Nim](https://nim-lang.org) will be an useful addition. Example of a Sublime Text extension that provides syntax highlighting support is available here: https://github.com/Varriount/NimLime

Other resource if first is not sufficient: https://github.com/nim-lang/Nim/wiki/Editor-Support

**Comment by sharkdp** [comment] 2019-04-11 19:13
Sounds good!

**Comment by sharkdp** [comment] 2019-05-31 19:13
Unfortunately, I wasn't able to generate a `.sublime-syntax` file from the NimLine `.tmLanguage` syntax.

**Comment by sharkdp** [comment] 2019-08-31 10:51
Closing this, as I see no way on how to proceed here. I'm not going to manually convert the `tmLanguage` file.

**Comment by Nindaleth** [comment] 2019-10-06 20:21
Not sure if anyone can still read this as the issue is closed...

But there's at least an option of `.sublime-syntax` workaround: https://github.com/Varriount/NimLime/issues/90#issuecomment-451684755
It's from October 2017 and kinda unmaintained, but between potentially incomplete syntax highlighting and _nonexistent_ syntax highlighting for Nim, you might prefer something over nothing.

**Closed** 2019-10-30 18:47 UTC
Labels: good first issue, help wanted, new-syntax

**Comment by sharkdp** [comment] 2020-03-22 12:55
This has been released in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).
