### ISSUE TITLE
Scroll for terminal supporting it

### ISSUE THREAD

**Issue by gjuchault** [sharkdp/bat#246] opened 2018-08-31 10:26 UTC
Hello,

Using iTerm2 "AlternateMouseScroll", I can scroll in `less` instead of using arrow keys.
Do you think that would work with bat ?

Thanks :)

**Comment by sharkdp** [comment] 2018-08-31 17:54
Thank you for your feedback.

This is a duplicate of #188 (and #193).

You should be able to use the fix suggested in #188. If that works, we should probably add it to the "Troubleshooting" section of the README.

**Comment by mike-mosher** [comment] 2018-08-31 23:30
@sharkdp: I [tweaked the bash function](https://github.com/sharkdp/bat/issues/158#issuecomment-417812003) provided by @achalddave to use RS instead of RF, and was able to get this to work on a Mac using the default Terminal app.  Hopefully this helps

**Comment by gjuchault** [comment] 2018-09-04 08:13
@mike-mosher The only thing with your script is that you always wrap the content into less, where bat has some nice detections about how to render (for example try `bat file | pbcopy` and you won't have line numbers, etc.)

Here is a working micro-tutorial (for macOS at least):

1. Write the following to `~/bat.pager.sh`
```
#!/bin/bash

less --tabs 4 -RF "$@"
```
2. `chmod +x ~/bat.pager.sh`
3. Edit your bashrc/zshrc and add the following alias:
```
alias cat="PAGER=~/bat.pager.sh bat --theme='mytheme'"
```
4. `source ~/.[zsh|bash]rc`

And this is working nicely

**Comment by mladenp** [comment] 2018-09-05 14:56
@gjuchault solution works for me, but its not perfect because it shows the end of file.
Is there any way to make it scrollable like less is by default?

**Comment by mike-mosher** [comment] 2018-09-07 11:17
@gjuchault @sharkdp Thanks for the updated process.  However, your suggestions don't work.  I'm using Mac OS and Terminal.app with Bash.  To get it to work, you need to substitute `RF` with `RS` in the .bat_pager.sh script.

**Comment by gjuchault** [comment] 2018-09-07 14:33
@mike-mosher `RF` works fine with me

**Comment by gibfahn** [comment] 2018-09-12 09:32
What does creating a shell script give you over just setting `export LESS="--tabs 4 -RF"`?

**Comment by sharkdp** [comment] 2018-09-12 18:11
The problem with using the `LESS` environment variable is that `bat` will pass command-line options to `less` which *might* overwrite the ones in the environment variable.

**Closed** 2018-09-26 16:04 UTC
Labels: documentation, duplicate

**Comment by sharkdp** [comment] 2018-09-26 16:09
I hope that things are now well explained in this README section: https://github.com/sharkdp/bat#using-a-different-pager
