### ISSUE TITLE
Scrolling in iTerm not working if I set `--pager="less -FR"` in bat config file

### ISSUE THREAD

**Issue by selrond** [sharkdp/bat#526] opened 2019-03-11 09:17 UTC
only works if I set `export BAT_PAGER="less -RF"` directly in my `.zshrc` - should the behaviour be the same regardless of where I set it?

**Comment by sharkdp** [comment] 2019-03-14 20:01
Thank you for your feedback. This is a duplicate of #509 which has been fixed already (but not yet released).

**Closed by sharkdp** 2019-03-14 20:01 UTC

**Comment by sharkdp** [comment] 2019-05-15 22:07
Fixed in [v0.11.0](https://github.com/sharkdp/bat/releases/tag/v0.11.0).
