### ISSUE TITLE
no highlighting on cygwin mintty

### ISSUE THREAD

**Issue by VladimirAlexiev** [sharkdp/bat#264] opened 2018-09-03 08:54 UTC
I use cygwin mintty, which has colors (eg I got a colored prompt).
- But when I `bat` a file, there are no colors.
- It doesn't page a long file (dosn't pipe it to `less`)
- If I manually page through `less`, there are still no colors

**Comment by sharkdp** [comment] 2018-09-03 17:53
I think this is a duplicate of #252.

**Closed** 2018-09-03 17:54 UTC
Labels: duplicate
