### ISSUE TITLE
.bash_profile is not colored by default

### ISSUE THREAD

**Issue by pavelrad** [sharkdp/bat#112] opened 2018-05-13 16:10 UTC
`.bash_profile` is listed under the bash section in `bat --list-languages`, but it's not colored by default. I have to run `bat -l bash .bash_profile` in order to get it colored.

**Comment by sharkdp** [comment] 2018-05-13 17:26
Thank you for your feedback. This is a duplicate of #100.

**Closed by sharkdp** 2018-05-13 17:26 UTC
Labels: duplicate
