### ISSUE TITLE
Pager closes upon resizing terminal window to a size that can show the entire file

### ISSUE THREAD

**Issue by agsimmons** [sharkdp/bat#1575] opened 2021-03-06 16:42 UTC
**Describe the bug you encountered:**

Using a small Konsole (terminal application) window, I used bat to open a file. As the contents didn't fit entirely on the screen, the contents showed up in the pager (less). I then enlarged the Konsole window to a size that would accomodate the entirety of the text, and the pager was quit instantly.

**What did you expect to happen instead?**

I expected the pager to remain open and the contents to continue to be viewable. If I use less on it's own, this is how it behaves. I've tested this on zsh and bash, and the issue is the same.

**How did you install `bat`?**

pacman on Arch

**bat version and environment**

#### Software version

bat 0.18.0

#### Operating system

Linux 5.11.1-arch1-1

#### Command-line

```bash
bat bug.md --diagnostic 
```

#### Environment variables

```bash
SHELL=/usr/bin/zsh
PAGER=less
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/home/andrew/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 563 (PCRE regular expressions)
Copyright (C) 1984-2020  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```

https://user-images.githubusercontent.com/4230365/110214043-bdc25a80-7e70-11eb-9728-36451e91236f.mp4

**Comment by sharkdp** [comment] 2021-03-07 20:08
Thank you for reporting this.

I have a similar setup:
* bat 0.18.0 (same)
* less 563 (same)
* konsole 20.12.3

and I can reproduce this bug with some files, but not all.

For example, the bug occurs with
* `src/error.rs`
* `src/lib.rs`

from `bat`s source. But it does not happen with
* `src/config.rs`
* `src/decorations.rs`

It can be fixed by using `--pager="less -R"` (instead of `--pager="less -RF"`, which is the default for this `less` version). 


And in fact it can be reproduced by calling `less -RF …` instead of `less`. So this seems like a bug in `less`, not in `bat`.

**Comment by sharkdp** [comment] 2021-05-13 09:22
The problem is still there with less 581.2. @agsimmons Would you mind reporting this upstream (https://github.com/gwsw/less/issues)?

**Comment by sharkdp** [comment] 2021-07-13 07:04
The upstream bug has been closed, so I guess this ticket can be closed as well. Should be fixed in less 588.

**Closed by sharkdp** 2021-07-13 07:04 UTC
Labels: bug, upstream-error
