### ISSUE TITLE
bat - filename completion script issue with init_completion error

### ISSUE THREAD

**Issue by maximillianus** [sharkdp/bat#2066] opened 2022-02-08 01:47 UTC
When I try to do autocomplete for the filename when using `bat`, I encounter init_completion issue. This happens in ~iTerm2. Strangely, in my regular terminal, it works fine~. It happens the same to my regular terminal.

Let's say I am trying to use bat to check `package.json`.

This is what comes up after I click <TAB> after typing `bat pac`
```
bat pac-bash: _init_completion: command not found
```
...

I would expect filename auto completion works fine ~in iTerm2 as it does in regular terminal~.

...

I install bat using homebrew and using it on iTerm2.

iTerm version: iTerm2 Build 3.4.15

---

```
#### Software version

bat 0.19.0

#### Operating system

Mac OS X 10.15.7 (Darwin 19.6.0)

#### Command-line

```bash
bat -pp --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS=<not set>
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/Users/apradana/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Less version

```
> less --version
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by myobie** [comment] 2022-02-16 10:43
Just in case anyone sees this and doesn't click through to the linked PR, I found out I had `bash-completion` version 1.3 installed and `bat` is expecting 2. 

I use homebrew, so I uninstalled `bash-completion` installed the formula `bash-completion@2` and that works fine. If you use another installation method, then maybe check your `bash-completion` version and upgrade if you can. If the linked PR lands, then it should work with both versions in the future.

**Comment by maximillianus** [comment] 2022-02-21 04:23
Thanks @myobie . This works for me. I uninstalled my `bash-competion` and installed `bash-completion@2`. Then I spawn a new terminal window and it works. It doesn't work when I immediately in the current terminal window, but that's minor.

**Comment by Enselic** [comment] 2022-03-03 05:22
Closed by #2074

**Closed by Enselic** 2022-03-03 05:22 UTC
Labels: bug

**Comment by Enselic** [comment] 2022-03-04 04:28
Thank you for reporting. Why call it "very similar" though? Looks like a different issue. 

Would be great if you or someone else can reproduce this on another machine. If so, it would be great if you could report it as a separate issue.

**Comment by polarweasel** [comment] 2022-04-05 00:50
> Thank you for reporting. Why call it "very similar" though? Looks like a different issue.
> 
> Would be great if you or someone else can reproduce this on another machine. If so, it would be great if you could report it as a separate issue.

Filed #2147 for this related issue.

**Comment by quinncomendant** [comment] 2023-11-02 00:04
> Just in case anyone sees this and doesn't click through to the linked PR, I found out I had `bash-completion` version 1.3 installed and `bat` is expecting 2.

For anyone else coming to this issue: replacing `bash-completion` with `bash-completion@2` does solve the errors, but keep in mind `bash-completion@2` requires bash version 4. If you use bash 3 (the default on even the latest macOS), you can't use `bash-completion@2`, which means you can't use bash completions at all for `bat`. So, just remove it (i.e., `rm /opt/homebrew/etc/bash_completion.d/bat`).
