### ISSUE TITLE
README.MD is not recognized as markdown

### ISSUE THREAD

**Issue by HakubJozak** [sharkdp/bat#807] opened 2020-01-20 16:50 UTC
README.MD is not recognized as markdown while README.md is. I suppose there is a case sensitive pattern for checking the file extension. Is it a bug or a feature?

I am willing to submit a PR but I am not Rust developers so pointers to the right lines would be appreciated ;)

**Comment by eth-p** [comment] 2020-01-20 19:03
I can confirm this bug.

I believe the issue is caused by how Sublime syntaxes specify their applicable file extensions. The highlighting library used by `bat` (Syntect) determines the syntax for a file extension using a case-sensitive comparison. I'm not sure if the Sublime syntax `file_extensions` field is intended to be case-insensitive or not, but depending on the answer to that, either Syntect or sublimehq/Packages isn't doing something correctly.


Unfortunately, it looks like [the Markdown syntax](https://github.com/sublimehq/Packages/blob/71fd0ec9e4b42c73e560d088a05ccc14ef0f54fc/Markdown/Markdown.sublime-syntax#L5) file that we use only specifies lowercase file extensions. I'm not sure how @sharkdp would prefer to handle it, but there's a couple options that I can think of:

1. Include `--map-syntax MD:md` in your bat config file.
This can be done without any changes to bat or the Sublime Packages repository.

2. Create a patch file for the Markdown syntax and patch it during the build process.
While it could work, I don't think it's an ideal solution.

3. Create an upstream issue about it.

**Comment by sharkdp** [comment] 2020-01-20 21:31
@HakubJozak Thank you for your feedback.

> I'm not sure if the Sublime syntax `file_extensions` field is intended to be case-insensitive or not, but depending on the answer to that, either Syntect or sublimehq/Packages is doing something incorrectly.

Third possible option: the uppercase `.MD` file extension should not really be supported because it's non standard. 

I think its correct that the `file_extensions` field is case-sensitive. The field is also use to match against full filenames, and some of these are case-sensitive (`PKGBUILD`, `CMakeLists.txt`, `Dockerfile`). Apparently, there are also some file extensions which are case-sensitive (`.M` for Objective C, see https://en.wikipedia.org/wiki/Objective-C).

So if this should be fixed, it has to be added to the Markdown syntax file.

**Comment by sharkdp** [comment] 2020-02-28 08:09
I'm going to close this for now. @HakubJozak If you feel that `.MD` should be supported, please open a bug report at https://github.com/sublimehq/Packages

**Closed by sharkdp** 2020-02-28 08:09 UTC
Labels: question, syntax-highlighting
