### ISSUE TITLE
bat prints strange characters - what am I doing wrong?

### ISSUE THREAD

**Issue by fluffynuts** [sharkdp/bat#2171] opened 2022-04-28 14:43 UTC
When attempting to bat a json file, instead of all the nice formatting and colors, I get: 
![image](https://user-images.githubusercontent.com/4669340/165778150-fb62672e-eb85-408c-a632-0342717c6000.png)

I've tried with cmd, pwsh, in and out of windows terminal. I've tried with a couple of different fonts (eg Hack, Cascadia Mono, CascaydiaCove NerdFont, and the venerable Consolas) but the output stays the same. I _assume_ I'm doing something wrong?

**Comment by Enselic** [comment] 2022-04-29 15:52
Can you share the output of `bat --diagnostic` please? Also please share the exact command you use, and ideally also the file itself in question, unless it is huge. In that case the first few lines is probably sufficient.

**Comment by keith-hall** [comment] 2022-04-29 20:52
Something similar was reported at https://github.com/sharkdp/bat/issues/1385, maybe the comments there help?

**Comment by fluffynuts** [comment] 2022-05-03 07:33
Yeah, encoding is the problem, and possibly the best fix is to enable system-wide utf8 as per https://www.tutorialexample.com/set-windows-powershell-to-utf-8-encoding-to-fix-gbk-codec-can-not-encode-character-error-powershell-tutorial/

**Comment by Enselic** [comment] 2022-05-04 19:10
Duplicate of #1385

**Closed by Enselic** 2022-05-04 19:10 UTC
Labels: bug, windows
