### ISSUE TITLE
winget support

### ISSUE THREAD

**Issue by alanlivio** [sharkdp/bat#2408] opened 2022-11-20 15:13 UTC
Besides choco and scoop, another package manager for windows is the [winget ](https://learn.microsoft.com/en-us/windows/package-manager/winget/) from MS itself. 
So should be interesting bat be installed by a `winget install sharkdp.bat` call. More info [here](https://github.com/microsoft/winget-pkgs).

**Comment by mrBen** [comment] 2023-02-10 12:31
That’s a duplicate of #1102

**Closed** 2023-02-10 12:34 UTC
Labels: feature-request
