### ISSUE TITLE
Umlauts in ISO-8859-1 not properly displayed

### ISSUE THREAD

**Issue by cloudyster** [sharkdp/bat#568] opened 2019-05-24 10:14 UTC
when working with files in ISO-8859-1 encoding umlauts are not properly displayed

```
> file i.xml 
i.xml: ISO-8859 text

> unalias cat
> cat i.xml
Hüsker Dü

> bat --plain --color never  i.xml
H�sker D�
```

Cheers,
Marc

**Comment by eth-p** [comment] 2019-05-24 17:33
I'm not able to reproduce the issue, unfortunately. I think GitHub or my browser is normalizing the encoding from your snippet above. Would it be possible to provide a small test file?

**Comment by cloudyster** [comment] 2019-05-27 05:50
Shure, here you are. I've had to change file suffix to .txt, github did not allow .xml.
[i.xml.txt](https://github.com/sharkdp/bat/files/3222016/i.xml.txt)

**Comment by sharkdp** [comment] 2019-05-28 19:24
Thank you for reporting this. `bat` only supports UTF-8 and UTF-16. I am currently not planning to add detection ("guessing") for other encodings. You probably know that you can use external tools like `iconv` to change the encoding:
```
iconv -f ISO-8859-1 i.xml | bat -lxml
```

I'm a bit surprised that `cat` seems to work for you. It doesn't work for me and shows the same "invalid UTF-8" character as `bat`:
```
▶ bat --plain --color never i.xml 
H�sker D�

▶ \cat i.xml 
H�sker D�
```

Is your terminal emulator configured to read ISO-8859? If I pipe the output of `bat` and `cat` to [`hexyl`](https://github.com/sharkdp/hexyl), we can see that the output is identical:
```
▶ bat --plain --color never i.xml | hexyl
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 48 fc 73 6b 65 72 20 44 ┊ fc 0a                   │H×sker D┊×_      │
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘

▶ \cat i.xml | hexyl                     
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 48 fc 73 6b 65 72 20 44 ┊ fc 0a                   │H×sker D┊×_      │
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```

**Comment by cloudyster** [comment] 2019-05-29 05:55
Hello David,
thank's for investigating. This seems to be a terminal/environment/encoding issue where bat behaves fine.
Just for the record: cat works as described above with gnome-terminal with UTF-8 encoding, when switching to ISO-8859-1 umlauts are displayed. 
I'm running urxvt (rxvt-unicode-256color) where bat/cat  behave as in the initial report.
Cheers,
Marc

**Comment by sharkdp** [comment] 2019-05-29 19:12
> I'm running urxvt (rxvt-unicode-256color) where bat/cat behave as in the initial report.

Right, I can confirm that. I think the issue is the following: in interactive mode (when the output is not piped somewhere else, like in my example above) `bat` will actually output `�` instead of the actual bytes (like `cat` does) because it *assumes* UTF-8 input.

Arguably, this is a feature and not a bug :smile:. Printing arbitrary bytes to the console could potentially mess up your terminal emulator. For a similar reason, `bat` does not print out binary files (in interactive mode).

**Comment by cloudyster** [comment] 2019-05-31 07:59
Hello David,

I agree that the current implementation is ok as far as I can judge the problem. Having a section in _Troubleshooting_ might be a good idea.

I've just hat a look at ```\cat --help``` - there is this ```-v/--show-nonprinting``` option which 
somehow corresponds to bat's  ```-A, --show-all```, but I like the idea/implementation in cat better.
By the way:  ```-v``` seems to be missing for the goal 
> Be a drop-in replacement for (POSIX) cat


Cheers,
Marc

**Comment by sharkdp** [comment] 2019-05-31 09:39
> I've just hat a look at `\cat --help` - there is this `-v/--show-nonprinting` option which
> somehow corresponds to bat's `-A, --show-all`

Well, `bat`s `-A`/`--show-all` option corresponds to `cat`s `-A`/`--show-all` option :smile:. The `-v`/`--show-nonprinting` option of `cat` does just a part of `-A`/`--show-all`.

> I like the idea/implementation in cat better.

Could you go into more detail? I spent quite some time designing `bat`s `--show-all` feature and would be grateful for feedback.

![image](https://user-images.githubusercontent.com/4209276/58696804-9c2d6880-8398-11e9-8f1f-c23b0f4d6eb4.png)
![image](https://user-images.githubusercontent.com/4209276/58696813-a18ab300-8398-11e9-8074-e2df53ae025e.png)


> By the way: `-v` seems to be missing for the goal
> 
> > Be a drop-in replacement for (POSIX) cat

Not really (see #134). `-v`/`--show-nonprinting` is not part of the POSIX standard.

**Comment by sharkdp** [comment] 2019-08-15 20:26
@cloudyster Any further feedback on this?

I see the following action points so far:
- [ ] Add a new option to `bat` to show the file "as-is". This could be the same option that is requested in #623 
- [ ] Add a section about encodings to the Troubleshooting section. This should mention `iconv` and the newly created option for `bat` from the previous point
- [ ] Handle non UTF-8 input in `bat -A`-mode. Instead of printing `�`, we could print `\xFC`.

**Comment by sharkdp** [comment] 2019-10-11 18:44
Closing this without resolving the first point. I'm not convinced we need this.

**Closed by sharkdp** 2019-10-11 18:44 UTC
Labels: documentation, help wanted, question
