### ISSUE TITLE
packaging conflict with hexyl

### ISSUE THREAD

**Issue by KennethNielsen** [sharkdp/bat#2021] opened 2022-01-10 08:32 UTC
Dear bat authors

I'm on Ubuntu and wanted to test out this tool, which looks really cool, but when I try to install another tool called hexyl, after I installed this one I got the following error:

```bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  hexyl
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 254 kB of archives.
After this operation, 697 kB of additional disk space will be used.
Get:1 http://dk.archive.ubuntu.com/ubuntu focal/universe amd64 hexyl amd64 0.6.0-2build1 [254 kB]
Fetched 254 kB in 0s (1,274 kB/s)
Selecting previously unselected package hexyl.
(Reading database ... 275097 files and directories currently installed.)
Preparing to unpack .../hexyl_0.6.0-2build1_amd64.deb ...
Unpacking hexyl (0.6.0-2build1) ...
dpkg: error processing archive /var/cache/apt/archives/hexyl_0.6.0-2build1_amd64.deb (--unpack):
 trying to overwrite '/usr/.crates2.json', which is also in package bat 0.12.1-1build1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/hexyl_0.6.0-2build1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

As you can see, it seems that both package wants to create a generally named file /usr/.crates2.json, which is also present in the hexyl package. I suspect this is an artifact of both being written in and built from rust.

The error in this case happenede when I installed hexyl, but I suspect it would have happened similarly had I reversed the order, since the root cause seems to be this generally named file.

I will create a similar issue on hexyl (https://github.com/sharkdp/hexyl/issues/148) and have cross linked them.

Thanks for the tool and any help you may be able to provide.

**What did you expect to happen instead?**

I expected the packging to be done in a manner where all files are kept somehow in name spaces related to the package, so that it can be installed alongside other tools written in rust without issues.

**How did you install `bat`?**

sudo apt-get install bat

---

**bat version and environment**

bat 0.12.1

Since this is a packaging issue, this part of the issue template seems not to be relevant.

**Comment by Enselic** [comment] 2022-01-10 09:32
Duplicate of #938

**Comment by Enselic** [comment] 2022-01-10 09:32
Try this workaround: https://github.com/sharkdp/bat/issues/938#issuecomment-646745610

**Closed by Enselic** 2022-01-10 09:32 UTC
Labels: bug

**Comment by KennethNielsen** [comment] 2022-01-10 18:44
Wow, there was a lot of duplicates. Must have forgotten to also search in the closed issues when I was looking to see if this had already been reported. Sorry about that.
