### ISSUE TITLE
Default pager breaks colours in Windows Terminal

### ISSUE THREAD

**Issue by rgwood** [sharkdp/bat#860] opened 2020-03-10 20:36 UTC
Hi, I've run into a bug in `less` that effectively breaks `bat` in the new Windows Terminal. I appreciate that this is not `bat`'s fault, but I'm reporting it here to save other people the investigation time.

## Bug

When calling `bat` in PowerShell in Windows Terminal, it breaks subsequent colouring in the terminal and makes it unusable (at least with my colour scheme) until the terminal is relaunched:

![image](https://user-images.githubusercontent.com/26268125/76355900-506a0100-62d2-11ea-95ad-b704839f32cb.png)

## Details

This occurs for me in PowerShell (7 and 5.1) in Windows Terminal, it does not occur in the old Windows PowerShell application.

I _believe_ this is due to [a bug](https://github.com/gwsw/less/issues/42) in version 551 of the `less` pager, which is installed by default with the `bat` Chocolatey package. The issue has been fixed in `less` source, but it's not available via Windows package managers yet.

## Short-term workaround

I was able to fix the issue by compiling [version 554](https://github.com/gwsw/less/releases) of `less`, using the MinGW compilation instructions [here](https://github.com/ScoopInstaller/Main/issues/834).

## Long-term fix

Wait for a newer version of `less` to be released via Chocolatey and Scoop.

**What version of `bat` are you using?**
bat 0.12.1 and less 551

**How did you install `bat`?**
Chocolatey

---
Windows 10 1909

**Comment by sharkdp** [comment] 2020-03-10 21:10
Thank you for the detailed bug report!

We can keep this open until it has been fixed in the Chocolatey package. Apart from that, I don't think there is anything we can do here except to suggest an (obvious) workaround, which would be to put `--paging=never` in `bat`s config file (`bat --config-file`):
```bash
# Disable paging
--paging=never
```

**Comment by sharkdp** [comment] 2020-04-11 09:01
Chocolatey:
- bat package: https://chocolatey.org/packages/Bat
- less package: https://chocolatey.org/packages/Less (currently still 551)

less 557 has been recently releases as a beta: http://greenwoodsoftware.com/less/download.html
The [release notes](http://greenwoodsoftware.com/less/news.557.html) mention *"Fix display bug in WIN32C version."*

**Comment by sharkdp** [comment] 2020-04-30 09:58
In the meantime, @gwsw released [`less v559`](https://github.com/gwsw/less/releases). It would be great if someone could verify, if it (still) solves this issue. It would be even better, if #887 could also be tested (see [this comment](https://github.com/sharkdp/bat/issues/887#issuecomment-616156939)).

**Comment by ofek** [comment] 2020-05-04 01:36
@sharkdp `less` no longer provides binaries 🙁 

- http://greenwoodsoftware.com/less/download.html#binaries
- https://chocolatey.org/packages/Less#comment-4887748012

**Comment by jftuga** [comment] 2020-05-05 14:27
I have built `less version 557` binaries for Windows.  I have also documented the complete  build process here:

https://github.com/jftuga/less-Windows

As a workaround, I have had good luck with really old versions of `less.exe` such as version 429 by setting the following environment variable:

    BAT_STYLE=numbers,plain

Please note that this workaround is **unnecessary** for binary I am distributing in my GitHub repo.

**Comment by jftuga** [comment] 2020-05-06 15:44
Note, I update my binary version of `less` to` v560` which fixes an issue where colors were not being properly displayed.

https://github.com/jftuga/less-Windows

**Comment by sharkdp** [comment] 2020-05-10 19:44
@jftuga Thank you very much for verifying this!

In this case, we only need to wait for the new releases to make it into Chocolatey/Scoop.

**Comment by jcotton42** [comment] 2020-05-10 19:45
@sharkdp unfortunately as @ofek noted `less` is no longer providing binaries and the maintainer of the Chocolatey package is also dropping it.

**Comment by jftuga** [comment] 2020-05-10 23:52
In addition to the Chocolatey information, under the [Paging](https://github.com/sharkdp/bat#paging) section, you could also link to my repo.

This could possibly be a resolution to this issue.

**Comment by ofek** [comment] 2020-05-11 02:41
@jftuga I'm using your builds, thanks!

**Comment by sharkdp** [comment] 2020-05-11 18:00
> @sharkdp unfortunately as @ofek noted `less` is no longer providing binaries and the maintainer of the Chocolatey package is also dropping it.

Oh, I missed the reference to the comment section of the Chocolatey package. That is unfortunate (not the fact that `less` does not distribute binaries, but the fact that Chocolatey does not build executables from source).

> In addition to the Chocolatey information, under the [Paging](https://github.com/sharkdp/bat#paging) section, you could also link to my repo.

I'd be okay with that, but I would much rather like this to be solved on the Chocolatey side. Maybe they could use the binary (binaries) from your repo?

**Comment by jftuga** [comment] 2020-05-11 18:30
I have messaged the Chocolatey `less` maintainer with the link to my repo.

**Comment by ofek** [comment] 2020-05-11 21:34
@jftuga Instead of (or in addition to) Chocolatey, can you please update Scoop? https://github.com/ScoopInstaller/Main/blob/master/bucket/less.json

**Comment by jftuga** [comment] 2020-05-20 15:57
Chocolatey is now using my version of less:

https://chocolatey.org/packages/Less

**Comment by ofek** [comment] 2020-05-20 16:09
@jftuga Yay! Would you mind doing Scoop too? I (& many I know) avoid Chocolatey.

**Comment by jftuga** [comment] 2020-05-20 20:58
@ofek I made a PR for scoop

https://github.com/ScoopInstaller/Main/pull/1108

**Comment by sharkdp** [comment] 2020-05-21 07:30
@jftuga Awesome work, thank you very much!

Can someone please confirm that the original bug has been fixed when freshly installing `bat` via Chocolatey?

**Comment by jftuga** [comment] 2020-05-21 11:22
I can confirm that this is fixed with `Chocolatey` and `bat 0.15.1` along with `less 561`. This was tested by using a fresh install of `bat` via `Chocolatey`.

**Comment by ofek** [comment] 2020-05-21 13:17
@jftuga Thank you!!!

**Comment by ofek** [comment] 2020-05-28 23:06
@jftuga fyi:

- https://devblogs.microsoft.com/commandline/windows-package-manager-preview/
- https://github.com/microsoft/winget-pkgs

**Comment by sharkdp** [comment] 2020-05-29 09:05
> @ofek I made a PR for scoop
> 
> [ScoopInstaller/Main#1108](https://github.com/ScoopInstaller/Main/pull/1108)

This has been merged as well :tada:. If anyone can confirm that everything works as expected when installing via Scoop, we can finally close this ticket.

**Comment by sharkdp** [comment] 2020-06-05 21:12
Anyone here using the Scoop-installed version of `bat`?

**Comment by patevs** [comment] 2020-06-05 23:38
@sharkdp Yes I have `bat` installed using `scoop`.

**Comment by sharkdp** [comment] 2020-06-06 15:10
Ok, I'm going to close this for now. Let me know if this should re-appear in some setting.

Thank you all for your help.

**Closed by sharkdp** 2020-06-06 15:10 UTC
Labels: bug, upstream-error, windows

**Comment by johnknoop** [comment] 2024-11-11 13:49
I don't know if this is same same issue resurfacing, or if it's new. But I have jftuga.less installed via winget, and all colors are stripped when running bat. Right now I've disabled paging in the Bat config file, because I value colors higher than paging, but it would be great if I could have both.
