### ISSUE TITLE
Ubuntu package information is wrong; claims the command is installed as `batbat`

### ISSUE THREAD

**Issue by saberworks** [sharkdp/bat#2082] opened 2022-02-19 02:55 UTC
**Describe the bug you encountered:**

On ubuntu 20.04 I `sudo apt install bat`
I notice that `cat` is no different and `bat` does not exist.
I read the `apt info bat` and it tells me:

>  In this package the executable and its manpage have been renamed from ‘bat’ to
 ‘batbat’ because of a file name clash with another Debian paclage.

However, `batbat` does not exist.  I think this should say `batcat` which does exist.  Also please notice `package` is misspelled as `paclage`.

**What did you expect to happen instead?**

According to the apt info, I expected to find a `batbat`, but instead it's actually  `batcat`

**How did you install `bat`?**

`sudo apt install bat`

---

**bat version and environment**
Ubuntu 20.04
bat 0.12.1

**Comment by Enselic** [comment] 2022-02-19 10:24
If it is the Ubuntu package that is problematic, why not report this to the Ubuntu bug tracker instead?

**Comment by sharkdp** [comment] 2022-02-19 12:56
This is also a duplicate of https://github.com/sharkdp/bat/issues/1613

**Closed by sharkdp** 2022-02-19 12:56 UTC
Labels: bug
