### ISSUE TITLE
Cyrillic files with cp-1251encoding are not displayed properly

### ISSUE THREAD

**Issue by junkntrash** [sharkdp/bat#622] opened 2019-08-06 08:18 UTC
Cyrillic files with cp1251 encoding are not displayed properly

Steps to reproduce:

1. Create a file with cyrillic content and save it in cp1251 encoding
2. Print it with bat

What I expect to see:

> привет как дела

What I actually see:

>������ ��� ����

**Comment by maxfilov** [comment] 2019-08-09 13:45
@junkntrash Is not `$ iconv -f CP1251 -t UTF8 <file> | bat ` enough? Something like
```batconv
#!/bin/bash

convert() {
    local input_encoding=$(enca -i -L russian $1)
    iconv -f ${input_encoding} -t UTF8 $1 
}

for path in "$@"
do
    convert "${path}" | ./target/debug/bat
done
```
should do the trick. This can be implemented in rust, but it won't be much faster or easier to use than iconv or enca

**Comment by sharkdp** [comment] 2019-08-10 11:20
`bat` only supports UTF-8 and UTF-16. I'm not planning to add support for other encodings, as there is generally no good strategy on how to detect file encodings (except for BOMs like in UTF-16). I don't want to add a "guess the file encoding" mechanism to `bat`.

**Comment by sharkdp** [comment] 2019-08-15 19:32
I'm going to close this ticket. Let me know if there is anything you think could be done here, in which case I can re-open it.

**Closed by sharkdp** 2019-08-15 19:32 UTC

**Comment by sharkdp** [comment] 2019-08-15 20:15
this is also a duplicate of #568
