### ISSUE TITLE
[Ubuntu] dpkg failed - .crates2.json file is already present in system

### ISSUE THREAD

**Issue by larden** [sharkdp/bat#2155] opened 2022-04-12 10:19 UTC
**Describe the bug you encountered:**
`bat` and `ripgrep` are using the same name of json file: '/usr/.crates2.json'

**What did you expect to happen instead?**

Installation succeed

**How did you install `bat`?**

```
$ sudo apt install bat
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libgit2-28 libhttp-parser2.9
The following NEW packages will be installed:
  bat libgit2-28 libhttp-parser2.9
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 2 009 kB of archives.
After this operation, 5 473 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://pl.archive.ubuntu.com/ubuntu focal/universe amd64 libhttp-parser2.9 amd64 2.9.2-2 [21,8 kB]
Get:2 http://pl.archive.ubuntu.com/ubuntu focal/universe amd64 libgit2-28 amd64 0.28.4+dfsg.1-2 [403 kB]
Get:3 http://pl.archive.ubuntu.com/ubuntu focal/universe amd64 bat amd64 0.12.1-1build1 [1 585 kB]
Fetched 2 009 kB in 2s (825 kB/s)    
Selecting previously unselected package libhttp-parser2.9:amd64.
(Reading database ... 298952 files and directories currently installed.)
Preparing to unpack .../libhttp-parser2.9_2.9.2-2_amd64.deb ...
Unpacking libhttp-parser2.9:amd64 (2.9.2-2) ...
Selecting previously unselected package libgit2-28:amd64.
Preparing to unpack .../libgit2-28_0.28.4+dfsg.1-2_amd64.deb ...
Unpacking libgit2-28:amd64 (0.28.4+dfsg.1-2) ...
Selecting previously unselected package bat.
Preparing to unpack .../bat_0.12.1-1build1_amd64.deb ...
Unpacking bat (0.12.1-1build1) ...
dpkg: error processing archive /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb (--unpack):
 trying to overwrite '/usr/.crates2.json', which is also in package ripgrep 11.0.2-1build1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

System information:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by SuperSandro2000** [comment] 2022-04-12 11:01
Dupe of those other 8 issues https://github.com/sharkdp/bat/issues?q=is%3Aissue+sort%3Aupdated-desc+crates2.json+is%3Aclosed

**Comment by Enselic** [comment] 2022-04-12 18:50
Duplicate of #938

**Closed by Enselic** 2022-04-12 18:50 UTC
Labels: bug
