### ISSUE TITLE
bat stalls when it encounters extremely long strings (bug / request?)

### ISSUE THREAD

**Issue by Adamkadaban** [sharkdp/bat#2164] opened 2022-04-23 01:16 UTC
I have a bash script with a ~120000 character b64 string. When bat encounters it, it stalls for a about 3 minutes. It takes just a second if outputting something closer to ~4000 characters.

Default install of bat. Installed using `dpkg -i bat*.deb`

#### Software version

bat 0.20.0 (0655ecf)

#### Operating system

Linux 5.16.0-kali3-amd64

#### Command-line

```bash
/bin/batcat linpeas.sh --paging=never --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS=<not set>
LANG=en_US.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/root/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 590 (GNU regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by keith-hall** [comment] 2022-04-23 06:18
Thanks for reporting. I believe we are tracking this under https://github.com/sharkdp/bat/issues/1658

**Comment by Enselic** [comment] 2022-05-05 05:28
Duplicate of #1658

**Closed by Enselic** 2022-05-05 05:28 UTC
Labels: bug
