### ISSUE TITLE
Files named `build` don't respect shebang lines

### ISSUE THREAD

**Issue by CarlOlson** [sharkdp/bat#685] opened 2019-10-10 16:45 UTC
Create a file named `hello`:
```ruby
#!/usr/bin/env ruby

puts "hello, world"
```

`bat hello` works just fine, but rename it to `build` and get no syntax highlighting. Or perhaps incorrect highlighting, but in this example I only see white text.

I might tackle this on the weekend if nobody jumps on it. I love the tool btw! <3

**Comment by sharkdp** [comment] 2019-10-10 18:18
Thank you for reporting this.

This is caused by `assets/syntaxes/Packages/C#/Build.sublime-syntax` which specifies `build` as a file extension for "NAnt build files"

As far as I understand, the files are actually called `XXX.build`, but Sublime Text syntaxes can not really distinguish between files called `foo` and files called `XXX.foo` (see also my footnote comment in #592).

That's kind of unfortunate, but the file name always takes precedence over the shebang.

Ideally, we could specify that this syntax file should only match `*.build` files and not files named `build`, but I don't think there is a good way around.

**Comment by sharkdp** [comment] 2019-10-29 19:23
Going to close this as a known limitation for now, with a possible fix coming in #592.

**Comment by cben** [comment] 2019-12-09 12:16
I'd expect `#!` line, when present in a file, is much more reliable than file name.  Can't we flip the priority so that `first_line_match` would win?

**Comment by sharkdp** [comment] 2019-12-09 22:07
> I'd expect `#!` line, when present in a file, is much more reliable than file name. Can't we flip the priority so that `first_line_match` would win?

Thank you for the feedback. I hadn't thought of that, but I think I would agree with you. We should try to change `bat`s behavior to prioritize shebang-detection.

I think we should also add a set of unit tests that make sure we have a well defined and consistent experience for things like this. We don't want this to change unexpectedly when we update some random submodule.

**Comment by keith-hall** [comment] 2019-12-10 13:05
My two cents:

I agree that a shebang line is more accurate than a file extension, or especially a file with no extension where the aforementioned path to syntax mapping doesn't exist.

But, what about where `first_line_match` doesn't represent/match a shebang line, but something different?
As a concrete example, I'm imagining having a specific syntax definition for SVG files. SVG files are just XML, so if `first_line_match` takes precedence, a `example.svg` file containing an XML prolog on the first line would be highlighted with the generic XML syntax definition instead of the more specific SVG one. This to me would be an undesirable regression. (This may be a bad example due to the `XML.sublime-syntax` containing `svg` in its `file_extensions` and priority being in reverse lexicographical order, but hopefully the point still stands...)

Is it then worth considering altering the priority of `first_line_match` vs `file_extensions` for only shebang lines? or making it configurable somehow? or what about checking the `file_extensions` first (but only the extension), followed by the `first_line_match` followed by the `file_extensions` against the base name when the file has no extension?

What do others think? Or is my scenario too unlikely/edge-casey to worry about? :)

I definitely like the idea of a test suite (and documentation) covering this behavior if it gets complicated :+1:

**Comment by CarlOlson** [comment] 2019-12-12 08:32
Unless I'm missing something, `first_line_match` is used very rarely (three times?)... and it is only used to match shebang lines. I think it would be acceptable to just ignore `first_line_match` and maintain a separate mapping of regular expressions to file types.

This order makes sense to me: `match contents` -> `match file location and name` -> `current match logic`

**Comment by keith-hall** [comment] 2019-12-12 12:14
it's used 23 times in the sublimehq/Packages repo, and not just for shebang lines:
https://github.com/sublimehq/Packages/search?q=first_line_match&unscoped_q=first_line_match

**Comment by sharkdp** [comment] 2019-12-15 19:36
> But, what about where `first_line_match` doesn't represent/match a shebang line, but something different?

Oh, good point!

> Is it then worth considering altering the priority of `first_line_match` vs `file_extensions` for only shebang lines? or making it configurable somehow? or what about checking the `file_extensions` first (but only the extension), followed by the `first_line_match` followed by the `file_extensions` against the base name when the file has no extension?
> 
> What do others think? Or is my scenario too unlikely/edge-casey to worry about? :)
> 
> I definitely like the idea of a test suite (and documentation) covering this behavior if it gets complicated +1

Good questions. I think we should first write the test suite and then think about this again.

Instead of just testing for "first line + file name => syntax" mappings, we could maybe just have a pool of "hello world"-like files for various languages. These would also be really useful to detect problems with regexes in highlighting syntaxes.

**Comment by sharkdp** [comment] 2020-03-10 22:08
> I think we should also add a set of unit tests that make sure we have a well defined and consistent experience for things like this. We don't want this to change unexpectedly when we update some random submodule.

I implemented a first version of the syntax-detection tests here: #861

**Comment by sharkdp** [comment] 2020-03-22 10:03
This has been fixed in #877 (see tests in `src/assets.rs`)

**Closed** 2020-03-22 10:02 UTC
Labels: feature-request, help wanted, syntax-highlighting

**Comment by sharkdp** [comment] 2020-03-22 12:51
This has been fixed in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).
