### ISSUE TITLE
Can't install bat on Ubuntu 20.04

### ISSUE THREAD

**Issue by Trid-collab** [sharkdp/bat#1537] opened 2021-02-05 13:33 UTC
I was trying to install bat on my Ubuntu 20.04 on WSL2 : I am getting the following error . I am a newbie to this

I was using sudo apt install bat

Unpacking bat (0.12.1-1build1) ...
dpkg: error processing archive /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb (--unpack):
 trying to overwrite '/usr/.crates2.json', which is also in package ripgrep 11.0.2-1build1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by SuperSandro2000** [comment] 2021-02-05 14:20
You have another Rust Package installed and Ubuntu packaged them incorrect that you can only install one package. Hirsuite has a fixed version which you could pin.

**Comment by sharkdp** [comment] 2021-02-07 21:37
Duplicate of #938

**Closed by sharkdp** 2021-02-07 21:37 UTC
Labels: duplicate, packaging/tooling
