### ISSUE TITLE
bat in tmux doesn't support mouse scrolling

### ISSUE THREAD

**Issue by alexlai97** [sharkdp/bat#904] opened 2020-04-04 12:10 UTC
`bat` in tmux doesn't support mouse wheel scrolling.
I know `less` can use mouse scrolling by given flag `--mouse`. 
Is `bat` supporting this feature right now ?

**Comment by sharkdp** [comment] 2020-04-05 11:39
Can you please post the output of the script at https://github.com/sharkdp/bat/blob/master/diagnostics/info.sh in order for us to get more information about your system?

**Comment by alexlai97** [comment] 2020-04-05 16:19
> Can you please post the output of the script at https://github.com/sharkdp/bat/blob/master/diagnostics/info.sh in order for us to get more information about your system?

system
------

**$ uname -srm**
Linux 5.4.28-2-lts x86_64  

**$ lsb_release -a**
LSB Version:	1.4  
Distributor ID:	Arch  
Description:	Arch Linux  
Release:	rolling  
Codename:	n/a  

bat
---

**$ bat --version**
bat 0.13.0  

**$ env**

bat_config
----------

**$ cat /home/alex/.config/bat/config**
```
#--theme="GitHub"
```

bat_wrapper
-----------

No wrapper script.

bat_wrapper_function
--------------------

No wrapper function.

tool
----

**$ less --version**
less 551 (PCRE regular expressions)

**Comment by sharkdp** [comment] 2020-04-08 08:16
Thank you for reporting this. I can reproduce it.

You can make this work by adding
``` bash
--pager="less --RAW-CONTROL-CHARS --quit-if-one-screen --mouse"
```
to `bat`s config file (`bat --config-file`).

Interestingly, things work just fine without the `--mouse` option outside of `tmux`.

To be honest, I hadn't heard of the `--mouse` option so far. This is quite new: http://www.greenwoodsoftware.com/less/news.551.html

We have recently added a way to detect the version of `less` within `bat`. I think we should use this to add `--mouse` in versions >= 551.

**Comment by nicm** [comment] 2020-04-08 09:32
It probably works outside tmux because the terminal in use sends fake Up and Down keys when the application does not support the mouse. tmux doesn't do this (although it is possible to configure it to).

**Comment by sharkdp** [comment] 2020-04-21 08:00
fixed in #928

**Closed** 2020-04-21 08:00 UTC
Labels: feature-request, good first issue

**Comment by sharkdp** [comment] 2020-04-21 14:07
I'm actually going to revert my pull request #928. Adding the `--mouse` option has a huge drawback: you cannot drag-select (and copy) text anymore :frowning_face:.

**Comment by nicm** [comment] 2020-04-21 14:08
In most terminals you can hold down Shift to bypass application mouse mode.

**Comment by sharkdp** [comment] 2020-04-21 14:11
True. That still works. But I personally find it highly irritating that I cannot drag-select normally.

What about passing `--mouse` conditionally if we are running inside tmux (if `$TMUX` is set)?

**Comment by nicm** [comment] 2020-04-21 14:17
Then you won't be able to use the mouse to enter copy mode if the mouse is enabled in tmux.

**Comment by sharkdp** [comment] 2020-04-21 14:25
I'm not sure I understand? I'm not a tmux user.

**Comment by nicm** [comment] 2020-04-21 14:31
tmux is a terminal as well - if less turns on the mouse, tmux's own mouse copy won't work in the pane running less, same as if you run less with `--mouse` outside tmux.

**Comment by sharkdp** [comment] 2020-04-21 15:07
Ok thanks. So do you propose to not use `--mouse` at all?

I'm going to leave it at the current behavior, unless someone tells me which logic to follow for `tmux`.

**Comment by nicm** [comment] 2020-04-21 15:08
Personally I would say that if the less developers thought the mouse should be on by default, they would have made it the default. Why not just let people who want it add it to `$LESS`? But it's up to you.
