### ISSUE TITLE
cat-like behavior while piping

### ISSUE THREAD

**Issue by johncf** [sharkdp/bat#35] opened 2018-05-01 15:41 UTC
I could use this as an shell alias for `cat` if it disabled all formatting/syntax-highlighting when it detects that the output stream is piped to another process (i.e. not a tty). But also have an option to force syntax-highlighting for use-cases such as `bat myfile.json --force-syntax-hi | head`.

**Comment by sharkdp** [comment] 2018-05-02 05:53
Thank you for your feedback.

This looks like a duplicate of #26

**Closed by sharkdp** 2018-05-02 05:53 UTC
Labels: duplicate
