### ISSUE TITLE
Fail to install using Cargo

### ISSUE THREAD

**Issue by dclong** [sharkdp/bat#1809] opened 2021-08-21 15:10 UTC
I got the following error message when install bat using Cargo. 
```
error: failed to compile `bat v0.18.2`, intermediate artifacts can be found at `/tmp/cargo-installIQhQLI`

Caused by:
  could not compile `bat`

Caused by:
  process didn't exit successfully: `rustc --crate-name bat --edition=2018 /home/dclong/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.18.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto -C codegen-units=1 --cfg 'feature="application"' --cfg 'feature="atty"' --cfg 'feature="clap"' --cfg 'feature="default"' --cfg 'feature="dirs-next"' --cfg 'feature="git"' --cfg 'feature="git2"' --cfg 'feature="lazy_static"' --cfg 'feature="paging"' --cfg 'feature="regex-onig"' --cfg 'feature="shell-words"' --cfg 'feature="wild"' -C metadata=f9c8024530844c77 -C extra-filename=-f9c8024530844c77 --out-dir /tmp/cargo-installIQhQLI/release/deps -L dependency=/tmp/cargo-installIQhQLI/release/deps --extern ansi_colours=/tmp/cargo-installIQhQLI/release/deps/libansi_colours-cbf3ec285a93568b.rmeta --extern ansi_term=/tmp/cargo-installIQhQLI/release/deps/libansi_term-037b61495b8a6ca9.rmeta --extern atty=/tmp/cargo-installIQhQLI/release/deps/libatty-3464d58c7120de64.rmeta --extern bugreport=/tmp/cargo-installIQhQLI/release/deps/libbugreport-b821dffe7855307c.rmeta --extern clap=/tmp/cargo-installIQhQLI/release/deps/libclap-6dc787251159b175.rmeta --extern clircle=/tmp/cargo-installIQhQLI/release/deps/libclircle-bde2eb931e53dbbd.rmeta --extern console=/tmp/cargo-installIQhQLI/release/deps/libconsole-e9a0c8ae95b4aba7.rmeta --extern content_inspector=/tmp/cargo-installIQhQLI/release/deps/libcontent_inspector-ce31692802ca6278.rmeta --extern dirs_next=/tmp/cargo-installIQhQLI/release/deps/libdirs_next-33bf3cac4e5bf100.rmeta --extern encoding=/tmp/cargo-installIQhQLI/release/deps/libencoding-5a1ac42f44a014a7.rmeta --extern error_chain=/tmp/cargo-installIQhQLI/release/deps/liberror_chain-cab8583e4352091d.rmeta --extern git2=/tmp/cargo-installIQhQLI/release/deps/libgit2-65bc15f5ac2a45eb.rmeta --extern globset=/tmp/cargo-installIQhQLI/release/deps/libglobset-eeed90d93e9a09e2.rmeta --extern grep_cli=/tmp/cargo-installIQhQLI/release/deps/libgrep_cli-156039e0160ca443.rmeta --extern lazy_static=/tmp/cargo-installIQhQLI/release/deps/liblazy_static-5116c2a3de2dd82e.rmeta --extern path_abs=/tmp/cargo-installIQhQLI/release/deps/libpath_abs-255fc6fa82b4c39a.rmeta --extern semver=/tmp/cargo-installIQhQLI/release/deps/libsemver-1d126d36d0353b07.rmeta --extern serde=/tmp/cargo-installIQhQLI/release/deps/libserde-fc2266f79655f50e.rmeta --extern serde_yaml=/tmp/cargo-installIQhQLI/release/deps/libserde_yaml-fa4538ab4e58b2b1.rmeta --extern shell_words=/tmp/cargo-installIQhQLI/release/deps/libshell_words-d81209a916926448.rmeta --extern syntect=/tmp/cargo-installIQhQLI/release/deps/libsyntect-094870d970489fe0.rmeta --extern unicode_width=/tmp/cargo-installIQhQLI/release/deps/libunicode_width-8c56cff4aead5932.rmeta --extern wild=/tmp/cargo-installIQhQLI/release/deps/libwild-8e8db0dcd5579853.rmeta --cap-lints allow -L native=/tmp/cargo-installIQhQLI/release/build/ansi_colours-968fd1f899642eb9/out -L native=/tmp/cargo-installIQhQLI/release/build/sys-info-24d9cbf35a58ea0d/out -L native=/tmp/cargo-installIQhQLI/release/build/libgit2-sys-273f3b42095ce03c/out/build -L native=/tmp/cargo-installIQhQLI/release/build/onig_sys-5058c7162f3cee7a/out` (signal: 11, SIGSEGV: invalid memory reference)
```

**What did you expect to happen instead?**

Install without issues.

**How did you install `bat`?**
```
cargo install bat
```

**bat version and environment**

bat: 0.18.2
OS: Ubuntu 20.04 in Docker
rustc: 1.54.0
cargo: 1.54.0

**Comment by Enselic** [comment] 2021-08-21 15:21
Strange that you get SIGSEGV, but probably a duplicate of #1796? Can you try to compile git master please?

**Comment by Enselic** [comment] 2021-08-22 17:33
We just made a v0.18.3 release, where #1796 is fixed, so if you try `cargo install bat` again, it should work. It worked for me at least.

I'm tentatively closing this as a duplicate. Please reopen if you still get problems with v0.18.3.

**Comment by Enselic** [comment] 2021-08-22 17:34
Duplicate of #1796

**Closed** 2021-08-22 17:34 UTC
Labels: bug
