### ISSUE TITLE
Incorrect Java highlighting

### ISSUE THREAD

**Issue by ro31337** [sharkdp/bat#247] opened 2018-08-31 17:19 UTC
```java
/*
  Test
 */
package test;
import test;

/**
 * Description
 */
public class Sample
{
}
```

Result:

![image](https://user-images.githubusercontent.com/1477672/44926719-404d8a80-ad07-11e8-8dfc-8dce93354327.png)

Expected:

Sample class to be highlighted as well.

**Comment by sharkdp** [comment] 2018-08-31 17:49
Thank you for reporting this.

This is a duplicate of #81.

**Closed by sharkdp** 2018-08-31 17:49 UTC
