### ISSUE TITLE
No output or wird output

### ISSUE THREAD

**Issue by TommyV6** [sharkdp/bat#2117] opened 2022-03-10 16:01 UTC
BAT does not show any output.

...

Display output of any file.

...

I tried many versoin: Zorin OS repo apt-get install bat (batcat)
dep from github
Ubuntu repo package

---

bat 0.20.0 (0655ecf)

#### Software version

bat 0.20.0 (0655ecf)

#### Operating system

Linux 5.13.0-30-generic

#### Command-line

```bash
bat -A /etc/hosts --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS=<not set>
LANG=pl_PL.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/root/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 551 (GNU regular expressions)
Copyright (C) 1984-2019  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```
https://ibb.co/jkwLqXJ

**Comment by Enselic** [comment] 2022-03-11 09:26
Is it `bat -A /etc/hosts` that shows nothing? Can you take a screenshot of the output of first `cat /etc/hosts` and then `bat  /etc/hosts` please? Including when you issue the commands. So just one screenshot.

**Comment by TommyV6** [comment] 2022-03-11 09:37
bat -A /etc/hosts is showing something, hard to tell what.
Screenshot:
https://imgur.com/a/Nkll9QQ

**Comment by Enselic** [comment] 2022-03-11 09:57
Looks like the default theme does not play well with your terminal, please read https://github.com/sharkdp/bat#highlighting-theme and try different theme(s)

**Comment by TommyV6** [comment] 2022-03-11 11:07
Ok, that fixes this issue. But about 80% of available themes do not work well with Zorin default terminal theme, the same thing with any Ubuntu light theme. Thx for the help!

**Comment by Enselic** [comment] 2022-03-11 16:13
Let's close this as a duplicate to the issue about detecting background color then.

**Comment by Enselic** [comment] 2022-03-11 16:13
Duplicate of #1746

**Closed by Enselic** 2022-03-11 16:13 UTC
Labels: bug
