### ISSUE TITLE
Continue to support GLIBC_2.28 in binary release

### ISSUE THREAD

**Issue by David-Else** [sharkdp/bat#2131] opened 2022-03-30 10:21 UTC
`0.19.0` worked fine on RHEL8/Centos8/RockyLinux8, but now `bat-v0.20-x86_64-unknown-linux-gnu.tar.gz` gives:
```
bat: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by bat)
bat: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by bat)
```
Maybe another binary might work? I am not sure what all the extensions mean.

Can you please keep on supporting GLIBC_2.28? Thanks!

**Comment by Enselic** [comment] 2022-03-30 11:26
Duplicate of #2106

**Closed by Enselic** 2022-03-30 11:26 UTC
Labels: feature-request
