### ISSUE TITLE
Add support for Dart syntax

### ISSUE THREAD

**Issue by andresaraujo** [sharkdp/bat#265] opened 2018-09-03 14:47 UTC
It would be nice if Bat supports Dart syntax, there this `.tmLanguage` I think we can use.

https://github.com/guillermooo/dart-sublime-bundle/blob/master/Dart.tmLanguage

**Comment by sharkdp** [comment] 2018-09-03 16:35
Sounds great

**Comment by sharkdp** [comment] 2018-09-03 20:30
Unfortunately, Sublime Text refuses to convert that `.tmLanguage` file to a `.sublime-syntax` file. It doesn't show an error message.

**Comment by tobenna** [comment] 2018-09-04 08:28
I used https://github.com/aziz/SublimeSyntaxConvertor to try converting it.
I think the issue is related to:
https://github.com/guillermooo/dart-sublime-bundle/issues/545

I took out 
https://github.com/guillermooo/dart-sublime-bundle/blob/d891fb36c98ca0b111a35cba109b05a16b6c4b83/Dart.tmLanguage#L912-L915
 and it converted just fine.

**Comment by sharkdp** [comment] 2018-09-04 13:16
@tobenna Thank you for investigating! Would you like to open a `bat` PR that adds the Git submodule and the converted `Dart.sublime-syntax`?

**Comment by tobenna** [comment] 2018-09-04 13:33
I'll open a PR :)

**Comment by sharkdp** [comment] 2018-09-05 18:52
fixed via #278

**Closed** 2018-09-05 18:52 UTC
Labels: good first issue, new-syntax

**Comment by sharkdp** [comment] 2018-09-12 20:45
Added in [v0.7.0](https://github.com/sharkdp/bat/releases/tag/v0.7.0).
