### ISSUE TITLE
Encoding Issue in Windows 10

### ISSUE THREAD

**Issue by bonfy** [sharkdp/bat#1127] opened 2020-08-04 09:49 UTC
**What version of `bat` are you using?**
bat 0.15.4

**Describe the bug you encountered:**
Encoding issue

**How did you install `bat`?**
scoop install bat

**Windows Version:**

Windows 10
OS Version:                10.0.17763 N/A Build 17763

---

bat a.txt

bat .\a.txt        
鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹攢鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹
€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€ 
      鈹?File: .\a.txt
鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹尖攢鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹
€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€ 
鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹
€   1   鈹 Hello world
   2   鈹
   3   鈹 Hello world!
   4   鈹
   5   鈹
鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹粹攢鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹
€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹

**Comment by sharkdp** [comment] 2020-08-15 12:42
What kind of terminal are you using?

**Comment by sharkdp** [comment] 2020-08-15 12:45
Also, what happens if you paste something like this into your terminal?
```
───────┬───────
```

**Comment by bonfy** [comment] 2020-08-17 00:50
Powershell

``` cmd
PS C:\> ─
```

![image](https://user-images.githubusercontent.com/3996876/90348066-a9e71080-e066-11ea-834d-38993e70ee06.png)

**Comment by sharkdp** [comment] 2020-08-17 19:33
(Powershell is the Shell, not the terminal). What kind of font is that? Could you try with the default font?

**Comment by bonfy** [comment] 2020-08-18 01:07
Use Windows cmd:

![image](https://user-images.githubusercontent.com/3996876/90458687-a66c8b80-e131-11ea-8e21-24f5a80d587a.png)

But when use `bat`, still the same:

![image](https://user-images.githubusercontent.com/3996876/90458891-33174980-e132-11ea-8c83-c6f04d4d72bf.png)

Maybe related to:

![image](https://user-images.githubusercontent.com/3996876/90458916-44f8ec80-e132-11ea-95cd-2ef0f2ce3410.png)

**Comment by sharkdp** [comment] 2020-09-07 19:25
This sounds like a duplicate of #537.

**Closed by sharkdp** 2020-09-07 19:25 UTC
Labels: bug, windows
