### ISSUE TITLE
Bash syntax highlighting not selected for *.ebuild and *.eclass files

### ISSUE THREAD

**Issue by vincentdephily** [sharkdp/bat#1292] opened 2020-10-08 13:54 UTC
**What version of `bat` are you using?**
bat 0.15.4

**Describe the bug you encountered:**
Bat didn't syntax-highlight [an ebuild file](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-apps/bat/bat-0.15.4.ebuild) despite `.ebuild` aledgedly being one of the recognized filename patterns. Using `bat -lbash` or `bat -l.ebuild` works around the bug.

Playing with file names reveals the issue: the `.ebuild` and `.eclass` patterns are mistakenly categorized as whole filename patterns instead file extensions patterns.

**Describe what you expected to happen?**
* All filename patterns mentioned in `bat -L|rg bash` should trigger bash syntax highliting.
* The docs should make it clear which patterns are whole-filename and which are extension

**How did you install `bat`?**
`emerge bat` and `cargo install bat` (two binaries, same behaviour).

---

system
------

**$ uname -srm**
Linux 5.8.13-gentoo x86_64

**$ lsb_release -a**
LSB Version:    n/a
Distributor ID: Gentoo
Description:    Gentoo Base System release 2.7
Release:        2.7
Codename:       n/a

bat
---

**$ bat --version**
bat 0.15.4

**$ env**
PAGER=/usr/bin/less

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 551 (PCRE2 regular expressions)

**Comment by vincentdephily** [comment] 2020-10-08 14:09
Updated bat to version 0.16.0, same issue.

**Comment by sharkdp** [comment] 2020-10-08 17:05
Thank you for the detailed bug report. I can reproduce this.


The issue seems to be that these two patterns are wrongly added with a leading dot in `sublimehq/Packages`:
https://github.com/sublimehq/Packages/blob/a275e61fe18cac70f0450bf3cef30dd83bcf895e/ShellScript/Bash.sublime-syntax#L27-L28

This could easily be fixed. However, the larger problem is that sublimehq/Packages is apparently moving to a new sublime-syntax format that is not supported by `syntect`, I believe :frowning:. I'm sure @keith-hall would know more about this.

Short term, we could fix this by adding a syntax-mapping to `bat` in `src/syntax_mapping.rs`.

If you want to have a local fix, you can add
```bash
--map-syntax '*.{ebuild,eclass}:Bourne Again Shell (bash)'
```
to `bat`s config file (see README)

**Comment by keith-hall** [comment] 2020-10-08 19:21
Yeah, syntect will need some major changes to cater for the latest `.sublime-syntax` features... One such one is https://github.com/trishume/syntect/issues/271

In the meantime, I guess we will have to stay on the current sublimehq/Packages submodule version and include/maintain a load of patches in this repository (or wherever we will keep them in future re https://github.com/sharkdp/bat/issues/1266#issuecomment-703905203)

**Closed** 2020-10-30 21:33 UTC
Labels: syntax-highlighting

**Comment by sharkdp** [comment] 2020-11-23 18:11
Fixed in [bat v0.17](https://github.com/sharkdp/bat/releases/tag/v0.17.0).
