### ISSUE TITLE
Spreadsheet sometimes not recognized as binary

### ISSUE THREAD

**Issue by xeruf** [sharkdp/bat#1974] opened 2021-12-08 09:18 UTC
**Describe the bug you encountered:**

I have two xslx files (unfortunately can't share them), which both have the following mime-type:

    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=binary

Both are binary, but somehow `bat` detects only one as such and tries to display the other, which is a garbled mess.

**What did you expect to happen instead?**

`bat` detects it as binary and does not try to display it

**How did you install `bat`?**

Arch Package

---

**bat version and environment**

#### Software version

bat 0.18.3 (b146958)

#### Operating system

Linux 5.15.6-arch2-1

#### Command-line

```bash
bat --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=less
LESS='--RAW-CONTROL-CHARS --ignore-case --LONG-PROMPT --jump-target=5 --incsearch'
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=OneHalfDark
XDG_CONFIG_HOME=/home/janek/.config
XDG_CACHE_HOME=/home/janek/.local/cache
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='less --squeeze-blank-lines +Gg'
```

#### Config file

Could not read contents of '/home/janek/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 590 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by Enselic** [comment] 2021-12-08 09:59
Thanks for taking the time to report a bug.

The heuristics for detecting if a file is binary is not perfect. David wrote some about it here: https://dev.to/sharkdp/what-is-a-binary-file-2cf5

I'm afraid we can't do much without a way to reproduce the issue you are having. For that reason, I'm not sure this issue is worth keeping open.

Maybe you can remove sensitive data from the problematic file to enable you to share it so we can reproduce your problem?

**Comment by xeruf** [comment] 2021-12-08 22:31
From my preliminary experiments removing the sensitive text makes it recognize the binary, I will try scrambling the text somehow...

**Comment by xeruf** [comment] 2021-12-09 14:08
This is weird: The relevant file was exported by Wekan - but if I re-save it in LibreOffice unmodified it is recognized as binary...

**Comment by xeruf** [comment] 2021-12-09 14:11
Confirmed: Any Wekan-Excel-export has this property. Here one with only test-data:
[export-board-excel-b8ccDtbGBDTJZqbWG.xlsx](https://github.com/sharkdp/bat/files/7685710/export-board-excel-b8ccDtbGBDTJZqbWG.xlsx)

**Comment by sharkdp** [comment] 2021-12-09 19:02
Thank you for sharing this.

Interesting! If we take a closer look at the binary content of this file …
![image](https://user-images.githubusercontent.com/4209276/145458633-fedbcf94-5dae-4ad7-8498-5611be1023e6.png)
… we notice that there are actually a lot of NULL bytes (0x00) in this file, so the heuristic described above should detect it as being binary.

However, in `bat`, we can not simply read the first N bytes to make a decision. We can only read the *first line of input* before we have to make a decision (because we want `bat` to work in streaming mode as well).

In this Excel file, there is a newline (0x0a) character at position 5. This means that `bat` only reads `50 4b 03 04 0a` before running the NULL-byte-heuristic.

**Comment by xeruf** [comment] 2021-12-10 11:37
maybe the first line being at least 50% non-printable characters is a useful heuristic?

**Comment by sharkdp** [comment] 2022-01-03 21:08
I'm not convinced, to be honest. I am inclined to close this as "won't fix". What do others think?

**Comment by Enselic** [comment] 2022-01-03 21:19
My gut feeling is that the heuristics can be improved. I'm thinking an iteratively expanded set of regression tests and iterative improvements of the heuristics is the way to go. But personally I would rather work on other things :)

I agree we can close this ticket in bat however. This is better to track over at https://github.com/sharkdp/content_inspector which we use to detect if files are binary.

**Comment by sharkdp** [comment] 2022-01-03 21:38
I want a binary-file-detector that is tuned towards decreasing false positives (as opposed to one that is tuned towards decreasing false negatives). I don't want to accidentally mark actual "text" files (e.g. including ANSI sequences) as binary. Because that would result in an even worse (and confusing) UX than accidentally writing some binary content to the console.

Fine tuning the heuristic in the above-mentioned sense would decrease false negatives, but likely generate some false positives.

**Comment by Enselic** [comment] 2022-01-03 21:42
Makes sense, I agree with your reasoning 👍

**Comment by xeruf** [comment] 2022-01-06 11:27
Can you name an example of a text file that starts with non-printable characters?

**Comment by sharkdp** [comment] 2022-01-06 12:00
> Can you name an example of a text file that starts with non-printable characters?

Yes. Every UTF-8 encoded file (which is the standard almost everywhere) that starts with non-ASCII characters. Like a text file in Cyrillic script. Or an Asian script.

Also, as mentioned above, some programs (like `bat`) print ANSI escape sequences to colorize text. If this output is stored in a file (or piped into `bat`), it might start with an escape character (`\x1b`). This is how `bat`s output starts, for example:
![image](https://user-images.githubusercontent.com/4209276/148379661-62d144e0-8b54-4f83-a30e-c54da7ba6425.png)

There is one non-printable character (`\x1b`), a few ASCII characters (green), and then a lot of non-printable bytes (the UTF-8 encoded version  of the `──────` separators.

**Comment by Enselic** [comment] 2022-03-30 11:34
Closing, as suggested in https://github.com/sharkdp/bat/issues/1974#issuecomment-1004359962

**Closed by Enselic** 2022-03-30 11:34 UTC
Labels: bug

**Comment by xeruf** [comment] 2022-09-26 00:04
Just stumbled upon this again: Wanted to inspect all files in a directory, one was a jar which bat tried to display (minecraft server jar), which was a tad annoying :/
