### ISSUE TITLE
Syntax highlighting by Unix shabang

### ISSUE THREAD

**Issue by RustemB** [sharkdp/bat#1628] opened 2021-05-02 09:46 UTC
Not sure, but this is useful for scripts without extensions
Probably need to add common executables to detect syntax/language, but it can be good feature

**Comment by keith-hall** [comment] 2021-05-02 09:51
This is already done for some (many?) syntaxes, where it makes sense. If you can mention some specific examples (i.e. Example shebang lines and which syntax it should be picked up as) where it isn't happening, then we can investigate :)

**Comment by keith-hall** [comment] 2021-05-02 13:21
I'm going to mark this as a duplicate of https://github.com/sharkdp/bat/issues/1545 - feel free to continue the discussion there :)

**Closed by keith-hall** 2021-05-02 13:21 UTC
Labels: feature-request
