### ISSUE TITLE
Bat displays escape code instead of colors, in some circumstances

### ISSUE THREAD

**Issue by ggciteo** [sharkdp/bat#1113] opened 2020-07-27 08:05 UTC
Hi,

I'm on freebsd. When i'm a regular user, verything is ok.
When I'm root, with 'sudo su -', bat displays escape code instead of colors.

TERM is screen
bat is installed via 'pkg install bat'

Here is the output of info.sh

system
------

**$ uname -srm**
FreeBSD 12.1-RELEASE-p7 amd64

bat
---

**$ bat --version**
bat 0.15.4

**$ env**

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 530 (POSIX regular expressions)

---

[paste the output of `info.sh` here]

**Comment by sharkdp** [comment] 2020-07-27 11:05
Thank you for reporting this.

> TERM is screen

Does it also happen in a normal terminal emulator? if you are not inside a screen session?

**Comment by ggciteo** [comment] 2020-07-27 15:35
Hi there,

I connect from within a tmux (screen-like) session.

Here is how : 
a> ssh b
b> tmux
b> ssh c
c> sudo su -
c$ bat plop.pl

The last 'bat' displays escape code.

It also fails without tmux:
(pick a keyboard, plug it, switch screen cable :) )
c> bat plop.pl # ok : display colors
c> sudo su -
c$ bat plop.pl # fail : display escape code

**Comment by sharkdp** [comment] 2020-07-27 20:31
Would it be possible for you to run `info.sh` in the `sudo su -` environment?

Please inspect the script first. It's not meant to be run with superuser privileges. I can't think of any problems it would cause, though.

Alternatively, please execute some of the steps manually. Environment variables, aliases, etc. would be interesting.

**Comment by sharkdp** [comment] 2020-07-27 20:32
Also: what happens if you run `bat` with `--paging=never`?

**Comment by ggciteo** [comment] 2020-07-29 07:10
Hi there,

--pagin=never displays colors :) 

And here is the output of info.sh under sudo su -

system
------

**$ uname -srm**
FreeBSD 12.1-RELEASE-p7 amd64

bat
---

**$ bat --version**
bat 0.15.4

**$ env**
PAGER=more

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------
Unable to determine if a wrapper function for 'bat' is set.
Unable to determine if a wrapper function for 'cat' is set.

tool
----

**$ less --version**
less 530 (POSIX regular expressions)

**Comment by sharkdp** [comment] 2020-07-29 11:51
>  PAGER=more

That is the problem. Please see #1063. You can fix this by setting `BAT_PAGER=less` or by adding `--pager=less` to your bat config file (see README).

Closing this as a duplicate of #1063.

**Closed by sharkdp** 2020-07-29 11:51 UTC
Labels: bug
