### ISSUE TITLE
Open file with `v`, like with `less`

### ISSUE THREAD

**Issue by NewAlexandria** [sharkdp/bat#1607] opened 2021-04-04 20:17 UTC
Pardon that I'm associating `bat` with `less`, but I've come to find it scan replace `less` in many circumstances.

`less` has a feature where pressing `v` opens the file in vim.  It's very handy.  

Would a PR on this feature be received well?

**Comment by eth-p** [comment] 2021-04-04 21:23
This isn't really something we can do at the moment. Under the hood, `bat` passes the formatted text to an external pager (by default, `less`) via STDIN. Once the pager starts, it's responsible for handling all user input. On the pager end of things, `less` doesn't really support the editor key (`v`) when paging from STDIN.

If/when #1053 becomes a reality, though, it would absolutely be received well!

In the meantime, an alternative would be to use `bat` as a preprocessor to `less` like so:

```bash
export LESS='-R'; # Force less to support ANSI colors.
export LESSOPEN='|bat --color=always --decorations=always %s'
```

Or, if you don't mind me shilling for my own tools that I use for similar purposes: [batpipe](https://github.com/eth-p/bat-extras/blob/master/doc/batpipe.md) is something that might help.

**Comment by sharkdp** [comment] 2021-05-12 10:01
Closing this as a duplicate of all the "Open editor with a key press" tickets in #1053.

**Closed by sharkdp** 2021-05-12 10:01 UTC
Labels: duplicate, feature-request
