### ISSUE TITLE
Slow to scroll to bottom for large files

### ISSUE THREAD

**Issue by YodaEmbedding** [sharkdp/bat#1784] opened 2021-08-06 10:58 UTC
**Describe the bug you encountered:**

1. Open a log file containing 100000 lines.
2. Go to bottom via keybind `G`.

**What did you expect to happen instead?**

Scroll to bottom immediately within 0.01s like `less`.

**How did you install `bat`?**

Arch Linux package.

---

**bat version and environment**

#### Software version

bat 0.18.1 (3aea514)

#### Operating system

Linux 5.12.14-arch1-1

#### Command-line

```bash
bat --diagnostic /var/log/pacman.log
```

#### Environment variables

```bash
SHELL=/usr/bin/zsh
PAGER=<not set>
LESS=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='sh -c '\''col -bx | bat -l man -p'\'''
```

#### Config file

```
--pager="less -FRX -I"
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version
less 581.2 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by Enselic** [comment] 2021-08-06 11:02
Duplicate of #304

**Closed** 2021-08-06 11:04 UTC
Labels: bug
