### ISSUE TITLE
no color for bat in ssh from a Windows client.

### ISSUE THREAD

**Issue by enihcam** [sharkdp/bat#865] opened 2020-03-14 06:19 UTC
I'm using `C:\Program Files\Git\usr\bin\ssh.exe` to connect to my linux host which has `bat` installed.

I have export `COLORTERM=truecolor`, and
- man with bat pager: color
- everything in tmux/screen: color
- bat <any file>: **no color**

**Comment by eth-p** [comment] 2020-03-14 23:32
What's the value of `$TERM`?

**Comment by enihcam** [comment] 2020-03-15 08:16
```
$ echo $TERM
cygwin
```

`--color=always` does not help.

**Comment by eth-p** [comment] 2020-03-15 09:50
> ```
> echo $TERM
> cage in
> ```

That is most likely your culprit. Try setting `export TERM=xterm-256color`.

**Comment by enihcam** [comment] 2020-03-16 01:20
Neither `export TERM=xterm-256color` nor `export TERM=xterm` work.
Yes, the decorations still print.

Thanks.

**Comment by eth-p** [comment] 2020-03-16 04:14
Thanks for checking. Two more things:

1. Is it any different if you use the built-in Windows 10 SSH command?

2. Could I have a bit more info about your Linux environment? Distro, version, etc. If you want to run the script in `diagnostics/info.sh` on your server, that would help me figure out how to create a similar environment.

**Comment by enihcam** [comment] 2020-03-16 07:57
Thanks for quick response @eth-p .
1. I'm using Windows 10 LTSC (the long term support version of Windows), which has no SSH in built-in program list.
2. 
```
$ ./info.sh
system
------

**$ uname -srm**
Linux 5.5.9-2-ck x86_64

bat
---

**$ bat --version**
bat 0.12.1

**$ env**

bat_config
----------

bat_wrapper
-----------

No wrapper script.

bat_wrapper_function
--------------------

No wrapper function.

tool
----

**$ less --version**
less 551 (PCRE regular expressions)
```

**Comment by eth-p** [comment] 2020-04-08 22:11
Sorry about the delay, and thanks for waiting.

After a little bit of experimentation, I found out how to reproduce this with git-bash. It's a very particular setup that requires you to use git-bash with the default Windows console (and not mintty).

![image](https://user-images.githubusercontent.com/32112321/78835933-eb272f80-79a5-11ea-8b12-f9ca71cdbec8.png)

To try and figure out what was going on, I printed the ANSI escape sequences generated by bat using `bat --paging=never sf.sh --color=always | bat -A -pp --color=never`:

```
␛[38;5;238m───────┬────────────────────────────────────────────────────────────────────────␛[0m␊
•••••••␛[38;5;238m│•␛[0mFile:•␛[1msf.sh␛[0m␊
␛[38;5;238m───────┼────────────────────────────────────────────────────────────────────────␛[0m␊
␛[38;5;238m•••1␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;243m#␛[0m␛[38;5;243m!/bin/sh␛[0m␛[38;5;243m␛[0m␊
␛[38;5;238m•••2␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;243m#␛[0m␛[38;5;243m•Copyright•2017•The•Chromium•OS•Authors.•All•rights•reserved.␛[0m␛[38;5;243m␛[0m␊
␛[38;5;238m•••3␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;243m#␛[0m␛[38;5;243m•Use•of•this•source•code•is•governed•by•a•BSD-style•license•that•can•be␛[0m␛[38;5;243m␛[0m␊
␛[38;5;238m•••4␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;243m#␛[0m␛[38;5;243m•found•in•the•LICENSE•file.␛[0m␛[38;5;243m␛[0m␊
␛[38;5;238m•••5␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;243m#␛[0m␛[38;5;243m•Write•an•error•message•and•exit.␛[0m␛[38;5;243m␛[0m␊
␛[38;5;238m•••6␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;243m#␛[0m␛[38;5;243m•Usage:•<message>␛[0m␛[38;5;243m␛[0m␊
␛[38;5;238m•••7␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;149mdie␛[0m␛[38;5;231m(␛[0m␛[38;5;231m)␛[0m␛[38;5;231m•␛[0m␛[38;5;231m{␛[0m␛[38;5;231m␛[0m␊
␛[38;5;238m•••8␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;231m••␛[0m␛[38;5;81mecho␛[0m␛[38;5;231m•␛[0m␛[38;5;231m"␛[0m␛[38;5;186mERROR:•␛[0m␛[38;5;231m$␛[0m␛[38;5;231m*␛[0m␛[38;5;231m"␛[0m␛[38;5;231m␛[0m␊
␛[38;5;238m•••9␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;231m••␛[0m␛[38;5;81mexit␛[0m␛[38;5;231m•1␛[0m␛[38;5;231m␛[0m␊
␛[38;5;238m••10␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;231m}␛[0m␛[38;5;231m␛[0m␊
␛[38;5;238m••11␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;243m#␛[0m␛[38;5;243m•Send•a•DCS•sequence•through•tmux.␛[0m␛[38;5;243m␛[0m␊
␛[38;5;238m••12␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;243m#␛[0m␛[38;5;243m•Usage:•<sequence>␛[0m␛[38;5;243m␛[0m␊
␛[38;5;238m••13␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;149mtmux_dcs␛[0m␛[38;5;231m(␛[0m␛[38;5;231m)␛[0m␛[38;5;231m•␛[0m␛[38;5;231m{␛[0m␛[38;5;231m␛[0m␊
␛[38;5;238m••14␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;231m••␛[0m␛[38;5;81mprintf␛[0m␛[38;5;231m•␛[0m␛[38;5;231m'␛[0m␛[38;5;186m\033Ptmux;\033%s\033\\␛[0m␛[38;5;231m'␛[0m␛[38;5;231m•␛[0m␛[38;5;231m"␛[0m␛[38;5;231m$␛[0m␛[38;5;231m1␛[0m␛[38;5;231m"␛[0m␛[38;5;231m␛[0m␊
␛[38;5;238m••15␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;231m}␛[0m␛[38;5;231m␛[0m␊
␛[38;5;238m••16␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;243m#␛[0m␛[38;5;243m•Send•a•DCS•sequence•through•screen.␛[0m␛[38;5;243m␛[0m␊
␛[38;5;238m••17␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;243m#␛[0m␛[38;5;243m•Usage:•<sequence>␛[0m␛[38;5;243m␛[0m␊
␛[38;5;238m••18␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;149mscreen_dcs␛[0m␛[38;5;231m(␛[0m␛[38;5;231m)␛[0m␛[38;5;231m•␛[0m␛[38;5;231m{␛[0m␛[38;5;231m␛[0m␊
␛[38;5;238m••19␛[0m•••␛[38;5;238m│␛[0m•␛[38;5;231m••␛[0m␛[38;5;81mprintf␛[0m␛[38;5;231m•␛[0m␛[38;5;231m'␛[0m␛[38;5;186m\033P\033%s\033\\␛[0m␛[38;5;231m'␛[0m␛[38;5;231m•␛[0m␛[38;5;231m"␛[0m␛[38;5;231m$␛[0m␛[38;5;231m1␛[0m␛[38;5;231m"␛[0m␛[38;5;231m␛[0m␊
```

The escape sequence `\ESC[38;5;___m` is used for selecting a color on a terminal with 256 color support. If I use the native Windows 10 ssh executable, it's perfectly capable of displaying those sequences:

![image](https://user-images.githubusercontent.com/32112321/78837037-1b6fcd80-79a8-11ea-9938-76ce62bdb137.png)

That means that it's not the terminal's fault that those colors are displayed incorrectly. It gets kind of interesting from here... Since Windows `ssh.exe` will read the colors correctly, I tried running that executable through the git-bash shell.

```bash
/c/windows/system32/openssh/ssh.exe [...]
```

![image](https://user-images.githubusercontent.com/32112321/78837345-b4064d80-79a8-11ea-88d0-a11f92c4de6f.png)

It resulted in the same issue with trying to display 256 colors. This suggests that the MSYS2/git-bash/cygwin environment is incapable of handling 256 colors, despite the Windows terminal being perfectly capable of it. To make sure, I ran the git-bash ssh executable from cmd:

```dos
\Program Files\git\usr\bin\ssh.exe [...]
```

![image](https://user-images.githubusercontent.com/32112321/78837575-3989fd80-79a9-11ea-92f8-fd919f5f9692.png)

And there's the issue... MSYS2. I suspect the MSYS2 environment is parsing the escape sequences and using the legacy `SetConsoleTextAttribute` API (which is only 16 colors) to actually display it. Colors that don't fall within the standard 16 (`\ESC[3_m`) are converted to white on grey instead.

---

**Conclusion:**
When running under the windows terminal, MSYS2 (the git-bash environment) tries to parse the ANSI color sequences. Since the terminal traditionally only supported 16 colors, MSYS2 helpfully converts everything outside the 16 color range to a white on grey color.

**Workaround:**
Use the mintty terminal with git-bash instead of the Windows terminal.

**Solution:**
Get `bat` to only output 16 color ANSI sequences. I'm not familiar with how to do this, though. Mentioning @sharkdp for feedback/help.

**Comment by enihcam** [comment] 2020-04-09 00:23
thanks for the details.
did you try tmux under Windows terminal? no idea why bat works in tmux whatever the terminal type is.

**Comment by eth-p** [comment] 2020-04-09 03:25
I haven't tried it, but if I have to take a guess, it's because tmux is a terminal multiplexer. A large part of that requires interpreting escape sequences and emulating a real terminal. Maybe it approximates the 256-color sequences as 16-color sequences as part of the process for rendering the pty's display?

Try running this inside tmux:

```bash
printf "\x1B[38;5;211mTest\n"
```

If it's 256 colors, it should show up as a warm pink. If it's being approximated, it might show up as pure magenta.

**Comment by enihcam** [comment] 2020-04-09 04:19
![image](https://user-images.githubusercontent.com/7010097/78857586-60553c00-7a5c-11ea-8274-c2016685809c.png)

**Comment by sharkdp** [comment] 2020-04-21 06:37
How can we continue here? Is this something that can be fixed in `bat`?

**Comment by eth-p** [comment] 2020-04-21 16:34
> ![image](https://user-images.githubusercontent.com/7010097/78857586-60553c00-7a5c-11ea-8274-c2016685809c.png)
> 

That looks a bit like it was changed to red (`\ESC[31m`) by tmux.

> How can we continue here? Is this something that can be fixed in `bat`?

The MSYS2 issue isn't really fixable by us, but we could work around the issue by having a simple way to force 16-color output (`--color=compatibility`?) from the config file.

**Comment by sharkdp** [comment] 2020-04-21 17:07
Thanks. That sounds good to me.

I would prefer `--color-mode=*auto*/24bit/8bit/off`. I have implemented the same option in github.com/sharkdp/pastel

We would then simply need to change this line:
https://github.com/sharkdp/bat/blob/70480ee9d4e4169c5436f3ab3a7fa1c18ff1849e/src/bin/bat/app.rs#L137

**Comment by eth-p** [comment] 2020-04-21 17:43
> Thanks. That sounds good to me.
> 
> I would prefer `--color-mode=*auto*/24bit/8bit/off`. I have implemented the same option in github.com/sharkdp/pastel

Sounds good. We would also need to support 4-bit color (ANSI 16 colors) to fix this issue. Should that be called "4bit" or "ansi"?

Does bat currently have a mechanism to convert to 4-bit color, or is it just 256/truecolor right now?

**Comment by sharkdp** [comment] 2020-04-21 18:08
Oh wait. We already have a way to fix this:
```
--theme=base16
```

**Comment by eth-p** [comment] 2020-04-21 20:58
> Oh wait. We already have a way to fix this

Sadly, it still emits 256-color escape sequences (`\ESC[38;5;___m`) when using the base16 theme. We need it to emit the 16-color sequences (`\ESC[3_m`) to make it compatible with terminals and environments that don't support 256 or truecolor.

```echo
echo "echo test" | bat -lbash -p --color=always --theme=base16 | bat --show-all -p
␛[38;5;6mecho␛[0m␛[38;5;7m•test␛[0m␊
```

**Comment by sharkdp** [comment] 2020-04-22 06:58
Ok, that actually looks like a bug to me. I have opened #934 to address this.

**Closed** 2020-04-22 08:22 UTC
Labels: bug, feature-request, windows, windows-msys2

**Comment by sharkdp** [comment] 2020-05-11 18:44
Please see the updates in [v0.15.1](https://github.com/sharkdp/bat/releases/tag/v0.15.1)
