### ISSUE TITLE
Broken layout with unicode

### ISSUE THREAD

**Issue by Kogia-sima** [sharkdp/bat#811] opened 2020-01-26 01:46 UTC
# :bug: Bug Report

## Description

File that contains unicode characters breaks the output layout.

It seems that `bat` regards the all input characters as single-width letter. However, if some line contains multiple-width character, the number of characters and the **true width** of line is different. That makes the `bat` split the line string at wrong position.

## Example

![0126_1036](https://user-images.githubusercontent.com/20660712/73129493-93289000-4028-11ea-9452-3d2fb6ac3f32.jpg)

## Possible Solution

Maybe [unicode-width](https://crates.io/crates/unicode-width) crate could solve this problem.

## Environment

| Software | Version |
| -------- | ------- |
| bat | 0.12.1 |
| qterminal | 0.14.1 |
| OS | Lubuntu 19.10 Eoan Ermine |

**Comment by sharkdp** [comment] 2020-01-26 06:39
This is a duplicate of #787

**Closed by sharkdp** 2020-01-26 06:39 UTC
Labels: duplicate

**Comment by sharkdp** [comment] 2020-03-22 12:52
This has been fixed in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).
