### ISSUE TITLE
Box-drawing characters can mess up the output and the terminal

### ISSUE THREAD

**Issue by Walther** [sharkdp/bat#551] opened 2019-04-26 05:33 UTC
Box-drawing characters can apparently break `bat`'s output, and they might not get displayed correctly. Additionally, it can be side-effecty and leave the terminal emulator / shell into a rather unreadable state, as seen in the screenshot.

<img width="1680" alt="Screen Shot 2019-04-25 at 22 20 39" src="https://user-images.githubusercontent.com/2943750/56785083-6cdb7880-67a8-11e9-9859-191ec53ee3c1.png">

Attached a text file for reproducability. It is a snippet from one of the output files of running [taurus](https://gettaurus.org/), a load testing tool.

[00_garble.txt](https://github.com/sharkdp/bat/files/3119796/00_garble.txt)

This was highly amusing to bump into 😄 but sadly perhaps more of a bug than a feature to keep around.

---
Context:
- MacOS Mojave 10.14.2 (18C54)
- iTerm2 Build 3.2.9
- zsh 5.3 (x86_64-apple-darwin18.0)

**Comment by eth-p** [comment] 2019-05-09 00:21
I am able to reproduce both issues (MacOS Mojave 10.14.3).

|Terminal.app|iTerm2|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/32112321/57416032-3bed4180-71b3-11e9-85a5-5276eb414e10.png)|![image](https://user-images.githubusercontent.com/32112321/57416076-735bee00-71b3-11e9-968e-f486b3e5a452.png)|

---

Issues occur both with and without paging.
Issues **do not** occur when `--decorations=never` (implies `--wrap=never`).
Issues **do not** occur when `--wrap=never`.

Opening up the file in `nvim` shows a bunch of escape sequences:

```
^[(0 -- Box Drawing ON
^[(B -- Box Drawing OFF
```

---

@Walther:

From my experimentation and analysis, the issue is that taurus is using the ANSI escape sequences for box-drawing rather than using the Unicode box-drawing characters. The use of ANSI escape sequences in character-level wrapping isn't *completely* supported, and basically amounts to a naive passthrough for SGR codes (which doesn't cover box drawing).

@sharkdp:

Would it be worth it to add a special case for box drawing characters?
It shouldn't be too complicated to match and handle `^[(0` and `^[(B` in a preprocessor step to replace the "box-drawing" characters with the unicode equivalents.

**Comment by Walther** [comment] 2019-05-09 00:27
Yep - i'm making a naive assumption/guess that `cat` explicitly makes sure the character changes are reset after EOF, making sure that even a "broken" input won't be side-effecty to the terminal - or something similar to that effect. Something to that effect would be nice to have in `bat` too

**Comment by eth-p** [comment] 2019-05-09 02:40
@Walther:

`cat` wouldn't be doing that. It turns out that I made some relatively-safe but incorrect assumptions when implementing escape passthrough for character wrapping. I improved it to more reliably detect any SGR escape sequences and those that use the CSI prefix. Everything else should be passed through properly now, including VT100 character set changes.

Your issue should be fixed in #561.

**Comment by Walther** [comment] 2019-05-09 02:50
Thank you for both the quick fix and the great explanations! ❤️

**Comment by sharkdp** [comment] 2019-05-10 16:12
@Walther Thank you for reporting this!
@eth-p Thank you for the analysis and the PR!

**Closed** 2019-05-10 22:52 UTC
Labels: bug
