### ISSUE TITLE
bat incorrectly displays session recorded with `script`

### ISSUE THREAD

**Issue by kbd** [sharkdp/bat#234] opened 2018-08-29 19:09 UTC
See screenshot:

![screen shot 2018-08-29 at 12 54 14 pm 2](https://user-images.githubusercontent.com/728060/44809594-613da080-ab8c-11e8-8af2-d2b3d30d44ef.png)

As you can see, I tried both regular `bat` output and `--style=plain`. Since a project goal is "Be a drop-in replacement for (POSIX) `cat`", I figured this was worth reporting.

Thanks for yet another awesome utility btw.

Edit: I thought I might have been incredibly stupid and that bat was doing some kind of highlighting for a .log file and that's why the display was incorrect, but I renamed it to .txt and the display was still incorrect. Also tried with `--color=never` and `--style=plain` to be sure and it was still incorrect.

**Comment by sharkdp** [comment] 2018-08-29 21:58
Thank you for reporting this. I can reproduce this.

Wow - it seems that these `script`-generated files reveal multiple problems.

First of all, as expected, everything works fine in loop-through mode (if we write to non-interactive terminals), as can be checked with
``` bash
bat session.log | cat
```
or by piping into another file.

Second, everything also seems to work if we disable wrapping, styling and the pager:
```
bat session.log --wrap=never --style=plain --paging=never
```

I start to see some unwanted `%` characters on the screen if I now enable either wrapping...
```
bat session.log --style=plain --paging=never
```

... or the decorations ...
``` bash
bat session.log --wrap=never --paging=never
```

... or both ...
``` bash
bat session.log --paging=never
```

Finally, things go really bad, if the pager is also enabled:
```
bat session.log
```

So it seems that both `bat` (which is responsible for the decorations and the wrapping) as well as `less` (the pager) have some problems with these control characters.

**Comment by kbd** [comment] 2018-08-29 22:38
> So it seems that both `bat` (which is responsible for the decorations and the wrapping) as well as `less` (the pager) have some problems with these control characters.

FWIW even `cat` has problems with some `script` recordings. There's a lot going on, with interactive syntax highlighting and so on. I also ran `ranger` (full-screen TUI app) in a recorded shell, exited it, then `cat`-ed the recording and it permanently broke my terminal :)

**Comment by kbd** [comment] 2018-08-29 22:54
Also, I should have uploaded my session.log, sorry.

[session.log](https://github.com/sharkdp/bat/files/2334057/session.log)

**Comment by eth-p** [comment] 2018-09-05 01:56
This is a pretty difficult situation. The ANSI sequences are doing some pretty interesting things in regards to changing the terminal's state and cursor.

For example, when the sidebar is enabled, any `CHA` (Cursor Horizontal position Absolute) sequences would end up placing the cursor over the sidebar instead of the content, which would end up garbling the content. This *could* be fixed by interpreting the `CHA` escape sequence and adding an offset to it, but then we run into another issue:

What if it's immediately followed by a `CUB` (CUrsor Backward) sequence? In a real terminal, it would do nothing because you can't move the cursor off screen. In this case, it would just move it onto the sidebar again. Not to mention, the terminal size would be different and some things might unexpectedly wrap (or fail to wrap).

To make it worse, there are even more complicated things to handle on top of that: How would we deal with the sequences for initializing the alternate screen? What about using the raw terminal mode? How about screen/scrollback clearing or removing parts of or entire lines?

We could add a bunch of hacky workarounds as a way to try and support as many different sequences as possible, but it doesn't seem practical and would more than likely be unmaintainable. An alternative could be to emulate a terminal and process the contents of the terminal screen instead of the file itself, but then we end up losing potentially important information (was there a `\n` there? is that a `\t` or 4 spaces?) and have a different output than the source file.

@sharkdp What's your take on this?

**Comment by sharkdp** [comment] 2018-09-05 18:57
@eth-p Thank you for the detailed analysis!!

> This is a pretty difficult situation.

This is why I called you in :smile: I was afraid it would be.

> We could add a bunch of hacky workarounds as a way to try and support as many different sequences as possible, but it doesn't seem practical and would more than likely be unmaintainable.

Absolutely agreed!

> An alternative could be to emulate a terminal and process the contents of the terminal screen instead of the file itself, but then we end up losing potentially important information (was there a \n there? is that a \t or 4 spaces?) and have a different output than the source file.

That also sounds way too complicated for too little benefit. As @kbd mentioned, there are even problems when using just `cat`.

So in the end, I think the best way to proceed here is to just accept this and to close the ticket.

If someone has more input on this or does not agree, please feel free to comment.

**Closed by sharkdp** 2018-09-05 18:57 UTC
Labels: bug, help wanted
