### ISSUE TITLE
Error while installing - Ubuntu

### ISSUE THREAD

**Issue by quotengrote** [sharkdp/bat#1861] opened 2021-09-24 08:34 UTC
**Describe the bug you encountered:**

I'll try installing bat with
``sudo apt install bat``,
the package got found and throws an error while installing.

Error:
```
mg@irantu 10:29 ~
> sudo apt install bat
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  bat
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/1585 kB of archives.
After this operation, 4325 kB of additional disk space will be used.
(Reading database ... 123213 files and directories currently installed.)
Preparing to unpack .../bat_0.12.1-1build1_amd64.deb ...
Unpacking bat (0.12.1-1build1) ...
dpkg: error processing archive /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb (--unpack):
 trying to overwrite '/usr/.crates2.json', which is also in package ripgrep 11.0.2-1build1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**What did you expect to happen instead?**

bat should get installed

**Version**

```
mg@ansible2 10:31 ~
> uname -a
Linux ansible2 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by aathif394** [comment] 2021-09-26 16:50
Have you tried removing this file? `/usr/.crates2.json`

**Comment by quotengrote** [comment] 2021-09-27 08:50
tried it, same:

```
mg@irantu 10:54 ~
> sudo rm /usr/.crates2.json
[sudo] password for mg:

mg@irantu 10:49 ~
> sudo apt install bat
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  bat
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/1585 kB of archives.
After this operation, 4325 kB of additional disk space will be used.
(Reading database ... 123213 files and directories currently installed.)
Preparing to unpack .../bat_0.12.1-1build1_amd64.deb ...
Unpacking bat (0.12.1-1build1) ...
dpkg: error processing archive /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb (--unpack):
 trying to overwrite '/usr/.crates2.json', which is also in package ripgrep 11.0.2-1build1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Enselic** [comment] 2021-09-27 10:25
Duplicate of #938

**Closed by Enselic** 2021-09-27 10:25 UTC
Labels: bug
