### ISSUE TITLE
Is it expected that Bat is rather slow on Windows?

### ISSUE THREAD

**Issue by stinos** [sharkdp/bat#1630] opened 2021-05-03 14:08 UTC
**How did you install `bat`?**

On Windows: via choco
On Ubuntu: `dpkg -i ...`

**bat version and environment**

All version 0.18.0 without anything custom.

Diagnostic output when running under PS:

#### Software version

bat 0.18.0

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
"C:\\ProgramData\\chocolatey\\lib\\Bat\\tools\\bat-v0.18.0-x86_64-pc-windows-msvc\\bat.exe" --diagnostic
```

#### Environment variables

```bash
SHELL="C:\\tools\\pwsh\\pwsh.exe"
PAGER=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of 'C:\Users\user\AppData\Roaming\bat\config': The system cannot find the path specified. (os error 3).

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

#### Less version

```
> less --version
less 563 (Spencer V8 regular expressions)
Copyright (C) 1984-2020  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```

**Description**

Using bat as preview in fzf isn't super nice because the delay in rendering is too obvious. I assumed this was merely rendering-related but some measurements show it's not just that. I started with

```
> (Measure-Command {bat c:\users\user\.gitconfig}).TotalMilliseconds
111.7591
```

which seemed a bit much for getting that file which is the same on all machines I tested afterwards:
```
> cat ~/.gitconfig | Measure-Object -Character -Line -Word

Lines Words Characters Property
----- ----- ---------- --------
   62   267       1780
```

For reference, this is what I get on an Ubuntu machine (which was under slight load):
```
~ $ hyperfine --warmup 10 'bat ~/.gitconfig'
Benchmark #1: bat ~/.gitconfig
  Time (mean ± σ):      64.5 ms ±   4.7 ms    [User: 53.7 ms, System: 9.9 ms]
  Range (min … max):    59.3 ms \u2026  77.4 ms    48 runs
 
~ $ hyperfine --warmup 10 'cat ~/.gitconfig'
Benchmark #1: cat ~/.gitconfig
  Time (mean ± σ):       1.6 ms ±   0.9 ms    [User: 1.0 ms, System: 0.4 ms]
  Range (min … max):     0.8 ms \u2026   4.6 ms    1537 runs
```
likewise on WSL on the same machine where I run Windows:
```
~ $ hyperfine --warmup 10 'bat ~/.gitconfig'
Benchmark #1: bat ~/.gitconfig
  Time (mean ± σ):      63.8 ms ±   5.0 ms    [User: 45.4 ms, System: 17.9 ms]
  Range (min … max):    57.4 ms …  77.2 ms    42 runs

~ $ hyperfine --warmup 10 'cat ~/.gitconfig'
Benchmark #1: cat ~/.gitconfig
  Time (mean ± σ):       4.5 ms ±   0.6 ms    [User: 0.8 ms, System: 4.8 ms]
  Range (min … max):     3.4 ms …  10.9 ms    460 runs
```

That same machine on Windows cmd.exe:
```
>hyperfine -w 10 "bat c:\users\user\.gitconfig"
Benchmark #1: bat c:\users\user\.gitconfig
  Time (mean ± σ):     102.9 ms ±   3.0 ms    [User: 2.4 ms, System: 4.5 ms]
  Range (min … max):    98.9 ms … 111.1 ms    26 runs

>hyperfine -w 10 "type c:\users\user\.gitconfig"
Benchmark #1: type c:\users\user\.gitconfig
  Time (mean ± σ):       0.3 ms ±   0.5 ms    [User: 2.8 ms, System: 3.7 ms]
  Range (min … max):     0.0 ms …   5.7 ms    288 runs
```

and in Windows Powershell:
```
> hyperfine 'bat c:\users\user\.gitconfig'
Benchmark #1: bat c:\users\user\.gitconfig                                                                                                                                          
  Time (mean ± σ):     108.5 ms ±   5.9 ms    [User: 7.4 ms, System: 3.6 ms]                                                                                                         
  Range (min … max):    99.6 ms … 119.1 ms    21 runs

> hyperfine 'type c:\users\user\.gitconfig'
Benchmark #1: type c:\users\user\.gitconfig                                                                                                                                         
  Time (mean ± σ):       1.3 ms ±   1.6 ms    [User: 2.8 ms, System: 5.2 ms]                                                                                                         
  Range (min … max):     0.0 ms …   8.2 ms    119 runs
```

Didn't create this as bug because I have no idea whether this is expected and/or some upstream problem?

**Comment by keith-hall** [comment] 2021-05-03 16:30
Thanks for reporting. There is a discussion at https://github.com/sharkdp/bat/issues/951 about bat's startup speed, which may interest you :)

**Comment by stinos** [comment] 2021-05-03 18:01
I've indeed seen a couple of seemingly related issues, but I'm wondering about the Windows specifics which I couldn't immediately find any information on. If there are other things I should measure/report just let me know.

**Comment by sharkdp** [comment] 2021-07-25 14:58
Thank you for reporting this. I'm afraid this is really just #951, but we might take another look at this once progress on #951 has been done (see comments in that ticket for some preliminary results).

**Comment by Enselic** [comment] 2021-08-04 07:00
The performance numbers really suggests this is the same as #951.

The answer to the question "Is it expected that Bat is rather slow on Windows?" is "No" :)

So I'm going to close this as a duplicate.

But we would love to get your help to benchmark this once #951 is solved (which we make good progress on).

Would it be OK for me to ping you in once there is something to try?

**Comment by Enselic** [comment] 2021-08-04 07:00
Duplicate of #951.

**Closed by Enselic** 2021-08-04 07:00 UTC
Labels: performance, question
