### ISSUE TITLE
bat breaks hyperlinks in command output

### ISSUE THREAD

**Issue by mcarton** [sharkdp/bat#961] opened 2020-04-29 10:20 UTC
**What version of `bat` are you using?**
bat 0.15.0

**Describe the bug you encountered:**
bat breaks [hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) in command output.

Eg. this

```
printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n' | bat -p
```

should be displayed as

```
This is a link
```

but is instead displayed as

```
8;;http://example.comThis is a link8;;
```

**Describe what you expected to happen?**
bat should not break hyperlinks.

**How did you install `bat`?**
`cargo install bat`

---

```
system
------

**$ uname -srm**
Linux 5.4.0-0.bpo.3-amd64 x86_64  

**$ lsb_release -a**
No LSB modules are available.  
Distributor ID:	Debian  
Description:	Debian GNU/Linux 10 (buster)  
Release:	10  
Codename:	buster  

bat
---

**$ bat --version**
bat 0.15.0  

**$ env**

bat_config
----------

bat_wrapper
-----------

No wrapper script.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 551 (GNU regular expressions)  
```

**Comment by sharkdp** [comment] 2020-04-29 11:38
Thank you for reporting this.

This is not a bug or missing feature in `bat`, but in `less`. You can see this by disabling the pager:
```
❯ printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n' | bat -p --paging=never
This is a link
```

and/or verify by running `less` instead:
```
❯ printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n' | less -RF
8;;http://example.comThis is a link8;;
```

**Comment by sharkdp** [comment] 2020-04-29 11:38
This can actually be fixed by using `-r`/`--raw-control-chars` instead of `-R`/`--RAW-CONTROL-CHARS`. So maybe it is a "bug" in `bat` after all :smile:. Why are we using the all-capital version of that option again?

**Comment by sharkdp** [comment] 2020-04-29 11:46
> Why are we using the all-capital version of that option again?

probably because of this warning in the man page regarding `--raw-control-chars`:

*"Warning: when the -r option is used, less cannot keep track of the actual
appearance of the screen (since this depends on how the screen responds to each
type of control character). Thus, various dis‐ play problems may result, such
as long lines being split in the wrong place."*

**Comment by mcarton** [comment] 2020-04-29 12:05
Oh, I didn't realize `bat` used `less`.
Feel free to close this issue then.

**Closed** 2020-04-29 16:12 UTC
Labels: upstream-error

**Comment by sharkdp** [comment] 2020-06-05 21:16
possible long term solution: #1053
