### ISSUE TITLE
Clicking a link on soft-wrapped line doesn't take into account the remaining of the link.

### ISSUE THREAD

**Issue by lesleyrs** [sharkdp/bat#2579] opened 2023-05-30 22:57 UTC
**What steps will reproduce the bug?**

1. zoom in the terminal before using bat so it line wraps
2. click link in bat with pager
3. it only links you to the first part of the link on the same line

**What happens?**

Opens only part of a link

**What did you expect to happen instead?**

Open up full link including soft wrapped part, doesn't occur if less wraps by itself.

**How did you install `bat`?**

cargo

---

**bat version and environment**

0.23.0 powershell (windows 10/windows terminal)

**Comment by keith-hall** [comment] 2023-05-31 03:13
I believe this could be a duplicate of https://github.com/sharkdp/bat/issues/2541

**Closed** 2023-05-31 08:04 UTC
Labels: bug
