### ISSUE TITLE
unmatched range specifier with "bat cache --init"

### ISSUE THREAD

**Issue by darkn3rd** [sharkdp/bat#276] opened 2018-09-04 21:34 UTC
### Steps

```bash
BAT_CONFIG_DIR="$(bat cache --config-dir)"
mkdir -p "$BAT_CONFIG_DIR/themes"
cd "$BAT_CONFIG_DIR/themes"```
curl -Os https://github.com/tmichel/sublime-terraform/blob/master/Terraform.sublime-syntax
bat cache --init
```

### Actual Result

```
[bat error]: Error while compiling regex '(output)\s+(")([\w-\.]+)(")\s*{': unmatched range specifier in char-class
```

### Expected Result

Thought that since this works in Sublime 3, it would work here as well.  Currently, as a workaround, I just comment out the element entry related to that regex.

```yaml
- match: '(output)\s+(")([\w-\.]+)(")\s*{'
  scope: entity.name.resource.terraform
  captures:
    1: storage.type.function.terraform
    2: string.terraform punctuation.definition.string.begin.terraform
    3: string.quoted.double.terraform
    4: string.terraform punctuation.definition.string.end.terraform
```

**Comment by sharkdp** [comment] 2018-09-05 18:29
Thank you for reporting this.

Unfortunately, Sublime Text uses its own Regex engine (which is not open source) and [syntect](https://github.com/trishume/syntect) can only try its best to imitate the behavior of Sublime Text.

I've seen this exact error with a few other Syntax files as well. They actually contain an error (in my view), but Sublime Text is a little bit more permissive with the syntax.

I think the problem is the `-` sign within the character class `[...]`. It should be escaped:
```regex
(output)\s+(")([\w\-\.]+)(")\s*{
```

There is nothing we can do here in `bat`, unfortunately. You could try to report this issue upstream (either https://github.com/tmichel/sublime-terraform or https://github.com/trishume/syntect), or just modify the file locally.

**Comment by sharkdp** [comment] 2018-09-12 20:32
@darkn3rd I'm going to close this. Let me know if there is any update.

**Closed by sharkdp** 2018-09-12 20:32 UTC
Labels: upstream-error
